* “让那些内外反动派在我们面前发抖罢，让他们去说我们这也不行那也不行罢，中国人民的不屈不挠的努力必将稳步地达到自己的目的。”

目录：前言、人生梳理、文章、侥幸

没有知识就没有世界，没有战略则很难通达。战略无处不在——三纲八目是儒士发展的战略原理，三纲规定了八目的目标，八目是不断更好地实现三纲的道路，四书五经是更详细的战术讲解，现当代战略则有一带一路、人类命运共同体，偏战术的则有三大纪律八项注意、八荣八耻、八礼四仪、五年高考三年模拟……

本文的目的是方便读者在我的某些作品（可能还有你的，简单点可以链接互通，学一下百年前的新民学会嘛。再扯远点，本文大概也可算作一个“自修大学”，虽然里面课程不少还有些稀烂）的帮助下审视过去生活、改进现有生活、准备未来生活。

——————

人生梳理

一件事、一类事、一整天，短期；一整年、一阶段、一辈子，长期。

一包四体五务七目，时分十二段十四类。

一包：《人生战略工具包》本文，包括此处所有。

四体：证明“人间值得”的生命质量“神秘体验”（相关文章未出）。心流、头脑清凉、合爱、精神飞翔。

五务：人生五件终身事务。身（身材、皮肤、肌肉、脑子，看摸动思，通向五体的途径）财（七目）学（听说读写日日新，包括有学习价值的“玩”、“娱乐”）友（标准：直谅多闻，求同存异；发展：修身交友，脱单合爱）政（“人是天生的政治动物”，人应当走向世界，创造未来）。

七目：财务上的“食房网电气水工”账目，足够的投入才有足够的产出。“食”是获取、储存和处理食材的不含燃料的费用，包括采猎工具和广义的厨具，“房”是获取人和物的不受人打扰的过夜空间的费用，在这个时代是花费较多甚至过半的，“网”是上网费及经常需要网络的手机电脑等设备的各种费用，“电”是电费和电灯空调等用电照明和暖通的设备的费用，“气”是用于家用/户外灶具、燃气热水器等的天然气、丁烷气等燃料的费用，“水”是水费和水龙头、水槽、花洒、浴帘、洗衣机、净水器、扫地机器人、吸尘器等工具的费用，毕竟水除了导热蓄热外基本就是用来除去污物的，泛化一下也没毛病，“工”是以上未用到或功能超出以上分类的其他工具和工作空间的费用，可单列，例如书籍、衣服、宠物、工作室、钓竿（坚持使用钓竿者一般除了渔获外还收获了快乐等）。

时分：一首主要为短期时间分类（“工学健厨吃洗睡、闲、聚、逝”，也可视作“账目”）的诗决，见《让时间管理成为本能》。
工学健厨吃洗睡，听说读写日日新。
闲入深林聚吞吐，逝者如斯未可移。

十二段：一般的线性的人生阶段，帮助认识和把握长期时间管理全局，见《人生阶段分析》。
胎婴幼小初高大，工婚育退暮。

十四类：基本生活物品及用法，帮助做好短期和中长期时间管理，见《基本生活用品参考清单》。过夜、洗澡洗衣、照明、电脑和台面、厨务、冰箱冰柜、暖通、拖地、家务机器、便器、健身、外出（12类家具），背包，备选。

——————

文章

时间管理：让时间管理成为本能https://zhuanlan.zhihu.com/p/143035959（主要帮助认识和改进短期时间管理）、多巴胺的现代劫持：超常刺激vs祖传刺激https://zhuanlan.zhihu.com/p/32041536（多巴胺与兴趣和动力有关，人最重要的是开心，但要注意避开有害的不自然的瘾，比如网瘾糖瘾撸瘾剁手瘾，它们经常是互相联系的）

工具：基本生活用品参考清单https://zhuanlan.zhihu.com/p/93387288（学会将相对常见的生活用品分为十二类并给出选购和使用细节从而高效舒适地室内户外生活、应对突发事件）、家具简单DIYhttps://zhuanlan.zhihu.com/p/103349232（制作常规和新式家具）、软件清单（不糟心和顺心的常用软件）

学习：通用核心书单https://zhuanlan.zhihu.com/p/129300500（十几种优中选优的好书和好文章，包括本文）、电子娱乐推荐https://zhuanlan.zhihu.com/p/103355338（玩中学，学中玩，精选音乐影视游戏等）

健身：随时随地健身体系https://zhuanlan.zhihu.com/p/127987958（文明其精神，野蛮其体魄，将动作从头到脚对应的自重训练为主的健身入门指南）、戒撸大师https://zhuanlan.zhihu.com/p/136040212（规避或戒除损害身心两方面的撸瘾可能还有别的网瘾糖瘾剁手瘾等，瘾通常互相联系）、现代丛林蜜藕（修身、交友、脱单、合爱：成为一个自己也会喜欢的更好的自己，培养和增强广谱社交能力，通过各种朋友和可能的伴侣满足更完整的归属需要，与性伴侣获取一般人不知道的神秘体验）、人类精神飞翔（精神飞翔，此生不虚）

饮食：原始饮食生活指南：入门学习https://zhuanlan.zhihu.com/p/36366663（实践更健康的原始饮食及其生活方式）、黄油评比https://zhuanlan.zhihu.com/p/141679770（银宝黄油为性价比之选、几种吃法）、达瓦里希，来点生蚝吗？https://zhuanlan.zhihu.com/p/142444222（吃生蚝的一些方面）


学生：新学生手册https://zhuanlan.zhihu.com/p/90613417（主要了解大学里的很多状况和注意事项，避免虚度极其珍贵的大学时光）

生活技能：c2驾考经验心得https://zhuanlan.zhihu.com/p/91841632（学车考驾照）


获取食材的其他方式：赶海指南https://zhuanlan.zhihu.com/p/63182207（动手搞野生海鲜）、iAVs鱼菜共生和WTF指南https://zhuanlan.zhihu.com/p/82582281（构建循环农业）

社会活动：海鲜公社——共享经济聚落https://zhuanlan.zhihu.com/p/131279778（在生产力进步得多的百年后的新时代，试着拉一圈特定的摆脱了冷气的人，以一起压榨常规生活模式下的人榨不干净的耐用品的价值为最主要的生存发展资料来源。组织形式：可近可远的物品交换、不住一起物品集中的短期营地和长期会所、至少住同小区的公社）

人生感悟：Walden·读《经济篇》，研究未来生存方向https://zhuanlan.zhihu.com/p/31989998（开始愁自己大学毕业后的人生应该是什么样）、老渔夫今天告诉我命运是什么样子的（寓言，附赏析、背景）https://zhuanlan.zhihu.com/p/125385100（寓言。与把我很大程度上钉在本地的工作首次正面接触，敬畏必然降临的现实和幻灭）

——————

侥幸

“譬如朝露，去日苦多”，从那些已经完成和将要完成的事看来，在97年生的我这样的年纪，我还算年轻，我已经算是很幸运了，有很多人被抛在更前面，而且他们没（认定自己）被赐予“解剖生活”的使命，他们只是在生活（这是很可惜的，因为他们的潜能往往远超他们的生活常规所用，却不巧就缺了个把强烈的念头，而只在业余把这些念头交给别人去演绎去投射），我过去有时为这样的对比而暗自（傻笑）或字里行间掩饰不住地感到侥幸，但另一方面，我有时也会不由自主地想到，如果我再早那么几年十几年知道并掌握我现在的这些工具该有多好。我知道把这些工具传送到过去是极不可能的，所以我既然解剖出了生活的这一层，那我就得寻求替代方案（“一个幽灵，怨悔过去的幽灵，在网络上游荡。”）……现在我是不需要什么替代方案了，我有的就是现在，希望每个人也一样拥有它。人后悔有早有迟，希望大家能在读到本文等契机后尽早把其中至少绝大多数后悔完，不要拖太晚，当然，性格本来就很好的人也不一定需要后悔，直接前进就完事了，别的人也可以抛下“个性”一样前进就完事了，然后也许性格和命运也会变得不错。