* （作于2021.3.1~3）
* 导图、脑图、大脑地图、思维的十字路口，简言之，用来检查、调整和升级思路。
* 交通道路一般有前后左右高低宽窄明暗快慢新旧之分，思路也一样（加上“态度”等联想，可以这么解释前面那串形容词：活动驶向世界、休息倒车入库、平等左转都等、自由直接右转、高升费力、降级下坡、包容自选道随便开、促狭加塞“争先恐后”、后六字请读者补充），由于人的工作记忆相当有限，思路上飞驰着的很多转瞬即逝的信息一般需要转述给外脑，而外脑的转述和展现形式受具体外脑特点影响，例如打字写文章时你可能发现：
** 1.文字在行内向右这一个方向推进。
** 2.推进到最右端后新打的字移到下一行。
** 3.构建文字之间联系的方式，首先是邻近，中间空上一行一般尚不足以影响我们的递进理解；其次是使用“一、（一）1.①”“项目编号”“无序列表”这些组织符号将文字赋予上下级结构；文内隔得距离较远的可以用“见上文”、文字颜色、文内目录/索引/链接等构成指路（乃至到达）的联系；文与文之间可以用关键词、标签等找到涉及共同点的文字。
* 这样的联系够了吗？
* 我想是不够的，这样的文路还不如骑车开车看到的快捷丰富——只朝一个方向开，从左到右遍历一段路后，再跳到更右边的一段路继续——忽略细节从整体看则相当于朝下（在每行文字的最右端；有端联想到洛伦兹力和左手定则——原来我的大拇指是车，“目光”/“眼神”是磁场啊/滑稽）扭动（“漂移”；搜标题时发现印象笔记一个功能，手写到靠边缘时自动扩大页面，这倒是）加飞跃（想到一初中就在ipad上玩的俯视越野游戏鲁莽赛车reckless racing），这样看虽然也还是感觉狭窄，但似乎也不是特别死板......
:PROPERTIES:
:id: 61f758d5-d8c0-4fbb-b768-1acbfa236755
:END:
* 但是它的十字路口在哪？（这里解释一下标题的中间部分（是怎么想出来的），crossroads是十字路口，cross是十字，包括斜着的“x”）
* 如果我们要探索这个世界的丰富可能性，就一定不能只朝一个狭窄的方向前进（我往北很快就要渡江）——“所以我写了很多文章、驶出了很多文路”——不错，但不够，这些路上飞驰的赛车，它们能看得见彼此、不会感到孤独、能够碰撞出思维的火花吗？
* “我可以写级别更高、乃至总括这一切的文章"——的确，然而那些结构复杂、一眼望不到边和整体大概的文路很可能成为只属于车手们的精彩（和可能的寂寞），如果车手们想要更多车手加入进来，加入到自己看得见的道，或者只是给观光游客树个“景区导览图（和您的位置）”的信息牌（“路牌”），那么就应该至少做份方便看的地图出来，把这些自己觉得有联系的地图更直接直观地联系起来——事实是，多数人更喜欢到达而不是道路，不过如果生活中多数情况下避不开道路，那我们希望这样的道路能少点不确定性，并且在确定的信息方面，这样的道路尽量足够——（“见前文”）“高宽明快新”（搜一下，高宽课程、HIghScope；明是回家看“激荡四十年·1978”看到字幕后加的；新是更后加的），高令人有所向往，宽让大家都能上，明让大家放胆开，快让大家——“信息高速公路”，同时也是“一条神奇的天路”。
:PROPERTIES:
:id: 65bcbf52-a6fd-43ce-8938-1aab91c18e72
:END:
* 有了有意思的导览图，游客也许是获益了，那么车手（再加个多义的类比：“操盘手”）在有点成就感（“有展览作品、陈列奖品的感觉”）、提升自我认识（在宏大画布上找到渺小自己的位置——“桅杆之顶，感觉良好”；以及路与路之间丰富的联系）、可能发展同行之外，还能收获什么？
* “这个世界的丰富可能性”。
* ——————
* 原来是整理《手电》时重搜文末关键词发现了厉害的老大哥的一个列表好奇点了进去，就觉得应该“试用”一下这个xmind，当晚还试了一个适合线下社交的游戏spaceteam......
“说声多谢马克丁啊？”“多谢，多谢马克丁！”
* （“今天的草稿就改到这里！”）