* 先在最好可同步的笔记/网盘软件内建个《入职材料》文件夹
入职材料主要由于不同企业的流程、标准、说明等的详尽和准确程度，可能会有不同程度的拖沓（时间摩擦成本），所以不确定就要问，并且为可能的麻烦做好准备。入职材料在入职后也可能用到。
* 手机号
** 部分行业部分岗位的号码要在自己名下，不能是家人等的副卡，可以打电话或用app查询是否在本人名下。此外可能也不推荐双卡双待，即一个手机只能放一张卡。
* 招工体检报告
通常半年内的有效。
带身份证和手机（健康码、行程卡、体检付款）到医院的体检中心，说招工体检和相关要求（若有）。时间方面，可能要在上午九点半之前到现场挂号，然后就开始体检，第二天下午两点后及之后若干天可取报告。体验前一天注意饮食睡眠等，午后最好不要喝咖啡等提神饮料，早吃早睡。体检当天空腹，不喝咖啡等提神饮料，喝水视体检项目和当前状况而定，早起不太早的话不要小便。
体检项目：血常规（一小针，棉球按几分钟）、身高体重、血压（提前和测时深呼吸可以降低）、眼（读数字辩色盲，然后是查近视，可能会图省事问戴不戴眼镜、驾照有没拿到、驾照体检有没过等，然后就5.0了）、耳鼻喉（“冰棍条”压住舌头说“啊”看喉咙，鼻子用金属“核桃夹”扩大点看，耳朵看看）、口腔（开口棉签）、内科（摸脖子背部等）、心电图（部分企业可能要图，而部分医院的招工体检报告本身不带，发现无图后要向医院提出打印，他们一般会保存相关图片）、胸片（胸部的X片，脱外衣，贴着机器吸气憋气）、彩超（部分企业可能要图，而部分医院的招工体检报告本身不带，发现无图后要向医院提出打印，他们一般会保存相关图片；成像效果更好的一种b超。在腹部涂润滑剂后用手持仪器接触腹肋，之后用纸擦掉）、尿检（用一小塑料杯取中段尿往一最多装10ml的小塑料管里倒）、早餐（可能含早餐，体检完了到后面餐厅吃，也许是一碗鸡蛋面，不想吃可以当沉没成本）
* 个人信息表
可能需要断断续续填几份，建议新建文件夹《个人信息》处理和保存相关材料并用笔记软件等同步，注意文件的更新和微信的传输之间可能不同步。
** 教育经历：一般从高中开始填。专科本科及以上的部分信息可参考学信网或教育部学历证书电子注册备案表（在学信网下载）。学校公办/民办也可能需要。
** 工作经历：如果没有关系或关系不全或路径不全，之前同行业在行业协会的记录就没法消掉。
** 过往成就/业绩：一般要写几行，没有工作经历也可以写学习时的（考的相关的从业资格也算），再就是对于未来的工作你（加上父母等人的配合）做了哪些相应的准备和规划（“职业规划”），以及打算怎么做，后面若有面试评价的内容可以参考并相应写。“过往”没有的就没有，现在和未来能画的很多。当然，准备着应付“职业规划”问题的内容可以不写在这。
** 家庭背景：工作单位和职务要填具体。
** 爱好与特长的区别
*** 特长一般不包括“特爱好”——“我特爱好玩电子游戏”（但玩大部分电子游戏很菜；那不如说具体点，玩什么电子游戏乃至其中的角色、武器等很牛）
* 承诺书
企业维护自身利益的突出告知条款。
* 保密协议
** 工资、职级等
* 待业承诺书
** 无工作经历的毕业生可能需要。
（注意：在求职前实际有工作经历的人即便之前因为怕面试为难也不要隐瞒企业交过社保的工作经历，否则到时候社保参保时无法作为新工作人员参保，这就和填过的信息表和承诺书不一致了。当然，如果之前企业没有交过社保，也有可能只是之前个人比如家人交过，可以停保）
* 其他
** 原件
半身免冠近照（实体大小一般一寸，电子版公司没事先说明的可以要相机原图和裁剪后的一寸。可能要穿西服，通常要与大家一致；注意有些地方只写宽高厘米单位，却不说像素或分辨率有时挺烦的，其实它们的意思可能是要“3乘4厘米”的比例，所以照片原件把高的像素按比例改了可能再压缩一下就行，如果有预览照片框则以是否铺满框为准，否则真的“3乘4厘米”照片反而显得古怪而不符合没写明白的标准）
报到证（一张蓝色的纸）
就业创业证（原就业失业登记证。到原社区居委会，一般有户口簿和一张2寸照片就行，补办一样）
** 复印件
无论是否有复印件，都建议带原件。如果没有复印件一般可以带原件过去当场复印。打印要完整，设置里要选背景图形。
身份证正反面复印件电子档：用WPS等的图片扫描功能把扫出来的身份证导出到A4纸大小的pdf文件里。
** 电子照片：就是jpg、png等格式的。一般备两三种文件大小的，方便某些考试等上传。
** 学历学位证书：通常包括高中的。与学校有关的可以装一个拉链袋。
** 英语、计算机等：CET可能网上查不到，所以纸质就够了。
** 从业资格：一般需要找到“打印合格证”之类的打印出来，如果真没证书、只有考试成绩的可能要截图，可能还要当场查询验证。
** 社保卡：可以在微信公众号“我的社保卡”绑定电子社保卡并查询状态。
** 银行卡：用来发工资，不同公司可能要求开不同银行的借记卡。
* 劳动合同
* 组织申请
** 工会：用来组织团建活动（所以一般要加）、发可能不需要的茶粮油米面（可以送人）等。打印两张表（网页上可能有模板）手写。
** 互助基金会：公司内的基金，帮助有大病、孩子上学等方面困难的员工及其家属。
* 网上培训
** 可能有若干小时的网上培训，学习价值较低的设闹钟挂着就行。
* 竞业协议
:PROPERTIES:
:id: 65bcbf53-2176-4e04-8c49-f10f3887140c
:END:
** [[https://www.zhihu.com/question/448015777][如何看待腾讯游戏两前员工因入职米哈游游戏公司违反竞业协议，被判各赔偿腾讯超百万元？]]
** [恐怖的竞业协议：互联网大厂在“吃人”_哔哩哔哩_bilibili](https://www.bilibili.com/video/BV1up42197mh)