* 这些是小说，谨防本文剧透
:PROPERTIES:
:background-color: #793e3e
:heading: true
:END:
* [刘慈欣小说中最强的文明是哪个？ - 知乎](https://www.zhihu.com/question/32076028)
* [最恨不得日本沉没的，就是日本人自己 - 知乎](https://zhuanlan.zhihu.com/p/163057388)
* 作品简评
:PROPERTIES:
:heading: true
:END:
** 按结尾的故事内时间排序
** 《镜子》
:PROPERTIES:
:id: 624d6760-9ef9-4232-a02a-ba4f7503fab3
:END:
*** 模拟真实宇宙、让世上一切隐私无所遁形的超弦计算机的宇宙模拟软件对若干人仕途和人类未来的影响。
** 《2018年4月1日》：昂贵延寿技术的不平等，程序员群体的暴动，单个程序员的贪污、情感与寿命抉择。
** 《地火》
:PROPERTIES:
:END:
*** [[https://baike.baidu.com/item/煤炭地下气化/10481151][煤炭地下气化]]
*** 27（晚在301至少是毕业后第一次在大几十人面前演讲）
**** 今天上午在坊子炭矿博物馆下井时，随着电梯的下降和历史的回溯，我不禁想到刘慈欣的《地火》，这篇如今看来已不太科幻的科幻小说主要讲的是对煤炭地下气化的狂想的大胆实验因为意外酿成惨烈事故的故事，而在小说更远的能源科技更先进的未来下井参观的学生在日记中写道——“过去的人真笨，过去的人真难”
**** 刚进坊子炭矿博物馆看的科普视频告诉我们，人类开采和利用煤炭的历史悠久，但如果把地球历史比作一天，那么相比地球生成煤炭的半天多时间，人类利用煤炭的历史甚至连10分钟都不到，在这10分钟里，数十上百代煤矿工人开采煤炭，面临着科技落后（相对我们和小说中未来那个时代）和殖民侵略对生命安全的威胁，因为生产力落后，煤矿工人需要使用低效的人力、危险的炸药、落后的金丝雀气体报警等勉强开采，而大自然会让所有准备不周、试图亲自改造她的人类付出代价，无论他们出于养家糊口还是变革生产方式的目的，而因为国力衰弱，在侵略者残暴统治下的煤矿工人需要长时间低薪欠薪工作，甚至因为达不到生产量而被日寇架在头上的铅坨砸伤甚至丧命，而与此同时，管理煤矿的德日侵略者却过着光鲜亮丽的生活——很难说科技落后还是国力衰弱对煤矿工人的命运影响更大，因为两者往往同时存在——“落后就要挨打”
**** 回到小说中未来学生的那句话，他说得对吗？过去的人真笨吗？人都是时代的产物，没法比较，甚至可以说那位学生的历史观是幼稚的、可悲的。过去的人真难吗？真难！没有过去的人为了科学进步和民族解放作出的牺牲，怎有我们安逸的现今和光明的未来？我们应该怎么看煤炭和面庞被煤粉染黑的煤矿工人呢？煤炭虽然黑暗，却为人类带来光明，希望我们也能为人类光明的未来贡献一份光，一份热
** 《三体》：弱小和无知不是生存的障碍，傲慢才是。
*** [[https://www.zhihu.com/question/265926035][《三体》中比尔·希恩斯的思想钢印对人类有什么实际意义？]]
*** [三体第一部——汪淼 - 知乎](https://zhuanlan.zhihu.com/p/54963796)
*** [《三体》中发动回归运动的文明为什么不惧怕被黑暗森林打击? - 知乎](https://www.zhihu.com/question/311622229)
**** “你把你小宇宙给我交了！”
:PROPERTIES:
:id: 65571075-78d2-4abe-a0af-e15393e354f7
:END:
** 《时间移民》：令人联想到辐射系列里的避难所的人体冷冻时间移民，对人类未来社会形态的畅想，；“全世界的大厅地板不错”
:PROPERTIES:
:id: 6289b9fa-30c1-464e-8133-e05cf5117a44
:END:
* 《山》
:PROPERTIES:
:id: 632db70f-1803-4a45-a724-f902b81b5af9
:END:
* 思想者
** 始于单恋的脱俗爱情
** 有不少或原创或转载的抑郁专家说，你看到的是八分钟前的太阳，而绝大多数恒星发出的光则要数万光年才能到达地球，就是太阳内部的光到达表层也需要几十万年，宇宙间光速传播周身一次就要耗费数十亿年，宇宙如刘慈欣《思想者》般不痛不痒，然而我想说，即便这么一小块，人脑被点亮一次，甚至也要隔个几十年
** [[http://music.163.com/song?id=34341364&userid=77770261][星空]]
** [[http://music.163.com/song?id=1296583155&userid=77770261][The Universe]]
* 赡养人类
** [[https://www.zhihu.com/question/39741645][如何评价刘慈欣的科幻小说《赡养人类》？ - 知乎]]
** 终产者
*** :PROPERTIES:
:id: 626f4741-3416-42c0-8afb-2fc1fff611c2
:END:
#+BEGIN_QUOTE
在一个秋天的黄昏，我从舷窗望出去，突然发现河边有一个人在跑步，我惊奇是谁这么奢侈，竟舍得在户外这样呼吸？仔细一看，天啊，竟是终产者！他慢下来，放松地散着步，然后坐在河边的一块石头上，将一只赤脚伸进清澈的河水里。
#+END_QUOTE
* [[http://m.sbkk8.com/xiandai/liucixinzuopinji/chaoxinxingjiyuan/211015.html][超新星纪元]]
:PROPERTIES:
:id: 659ca718-0831-4d20-8bb8-676bf8c8ae11
:END:
** [[https://zhuanlan.zhihu.com/p/134426776][人类命运思想实验--刘慈欣作品《超新星纪元》书评]]
** 模拟国家与卢安克
** 大学习
** 消防滑筒（也许中学时也想到过，但好像是消防滑梯。常见的是那种团队培训用的竖直下落然后一圈人接住滑下来的人）
** playful
** 复用中国2185部分段落（巨型）
*** 在二百米深处的地下机房中，圆柱体主机上的指示灯疯狂地闪成一片。与主机房隔离的冷却机房中，冷却机组以最大功率工作，把大流量的液氦泵入巨型电脑的机体内，使超导量子电路保持在接近绝对零度的超低温 状态下运行。在电脑内，高频电脉冲的台风在超导集成电路中盘旋呼啸，0和1组成的浪潮涨了又落落了又涨……如果有一个人缩小几亿倍后进入这个世界，他首先看到的是一个惊人繁乱的景象：在芯片的大地上，上亿条数据急流在宽度仅几个原子的河道中以光速湍急地流着，它们在无数个点上会聚，分支，交 错，生成更多的急流，在芯片大地上形成了一个无边无际的复杂蛛网。到处都是纷飞的数据碎片，到处是如箭矢般穿行的地址码；一个主控程序在漂行着，挥舞着无数支纤细的透明触手，把几千万个飞快旋转着的循环程序段扔到咆哮的数据大洋中；在一个存贮器的一片死寂的电路沙漠中，一个微小的奇数突然爆炸，升起一团 巨大的电脉冲的蘑菇云；一行孤独的程序代码闪电般地穿过一阵数据暴雨中，去寻找一滴颜色稍微深一些的雨点……这又是一个惊人有序的世界，浑浊的数据洪流冲过一排细细的索引栅栏后，顷刻变成一片清澈见底的平静的大湖；当排序模块像幽灵似地飘进一场数据大雪时，所有的雪花在千分之一秒内突然按形状排成了无限长的一串……在这0和1组成的台风暴雨和巨浪中，只要有一个水分子的状态错了，只要有一个0被错为1或1被错为0，整个世界就有可能崩溃！这是一个庞大的帝国，在我们眨一下眼的时候，这个帝国已经历了上百个朝代！但从外面看去，它只是一个透明护罩中的圆形的柱体。
:PROPERTIES:
:id: 62fe0d13-ed4a-4806-b191-55719bec60b2
:END:
*** 一个蓝色的星球在太空中出现了，像一个发着蓝光的水晶球悬浮在宇宙无边的夜海之中，表面上分布着旋涡状的雪白云带。她看上去是那么脆弱，仿佛轻轻一触就会破碎，她那天蓝色的血液就会漏到冷寂的太空中。
* [[https://www.douban.com/group/topic/83737035/][不能共存的节日]]
:PROPERTIES:
:id: 61a019c7-9be3-43b2-8705-d57a09918640
:END:
** ((633175cc-ef78-40e6-baac-c1063e1ff45c)) （“人类想象得到的”；那些“消失”了的文明）
** [[元宇宙]]
** [[https://xw.qq.com/cmsid/20210828A04U1000?f=newdc][刘慈欣，中国第一位“元宇宙架构师”]]（剧透）
** 相关小说（“哪天来个比较大的主题阅读——人类未来存在方式”）
*** 中国2185
:PROPERTIES:
:id: 659ca718-41e3-4efe-acfc-87a9b09c9573
:END:
超新星纪元
时间移民
三体
2018年4月1日
*** [[https://new.qq.com/omn/20211013/20211013A03Q6G00.html][除了《雪崩》，这5部科幻小说也写过元宇宙]]
*** 在虎鲸群的相关评论（剧透）
**** 这个元宇宙，我总想到刘慈欣的《时间移民》（对社会发展史的幻想），还有几年前的一篇有类似内容的笔记
***** 剧透一下知道的，中国2185是之前分享过的89年苏联尚未解体时的老作品，里面的元宇宙主要是网民以虚拟形象进入并智能汇总合成意见为几个较大的虚拟公民（也算是代表了）人民大会（不需要一层层的实体代表，每个人能上网都能进，部分人有vr设备接入），这个超新星纪元里也有，孩子政府在全国电脑总网的终点“大量子”（人工智能量子超算）的协助下与全国公民对话；还有就是之后通过脑部分子扫描在巨型机中意识复活的公民进入全国电脑总网后发生的黑客帝国般的剧情，也许算未受控的元宇宙以及全民公投（相对于民主集中）对现实世界的反噬
** 阅读笔记
*** 这个G让我想到银河系搭车客指南的主角的外星作家朋友福特大老爷
*** 刘慈欣描绘2050年北京才搞出非侵入式（侵入式会动手术往里插电极什么的）脑机接口（“大脑感应头盔”，可能还不完全贴头皮）和脑电波转文本（一句话试了四次校正完毕，应该说机器学习挺快的；谐音似乎也能看出大刘调皮的恶趣味），也许我们的现实能更快——而这是2016年的作品——在现实面前，科幻（又？）输了？
*** 丁仪（想名字逻辑：“定义”——“逻辑”）宇宙出新替身了，丁一博士
“2050年还在用扫帚”
双十一挨批，彩虹人震怒（“现在节日的数量还在很快增加中，像双棍节（注：一个同性恋者网络购物节）什么的。”）
*** G说话了，大刘炒冷饭或复用《时间移民》了，或者说好听点，描绘得更通俗了点
*** 人类科技的作茧自缚或内卷——元宇宙与黑域的比较
大刘在本篇中抛出担忧，人类沉迷元宇宙娱乐至死，可能逐渐地就不去研究有意义但充满麻烦、障碍、失败的航天等让人类离开子宫或摇篮的科技了，其最终效果堪比黑域（并且抛出了对“人类文明为何孤独”的一种解释：就像充满着猜疑链和先发制人的黑暗森林，其他智慧文明也在元宇宙中迎来了自己的流产或葬礼），光速极小的黑域相对外界其中一切都发生得极慢，而思维接近光速的元宇宙主机相对外界其中一切都发生得既快又理想，但共同点都是人类再也不能或不会离开地球
*** #+BEGIN_QUOTE
“你知道我们在做什么？”有人问，像以前创造历史的科学家一样，他们多少意识到这个突破的意义，但也没有十分把握，因为许多当时看似划时代的成果都淹没于时间之中，他们此时只有项目完成后如释重负的轻松感。一个勤杂工居然对这个成果如此兴奋，让他们很好奇。
#+END_QUOTE
**** 终于看到在搜索预览中就吸引我的这段路，不知道第几回感同身受、英雄相惜了属于是
**** #+BEGIN_QUOTE
时间碾碎万物，一切都因时间的力量而衰老，在时间的流逝中被遗忘。——亚里士多德
#+END_QUOTE
*** 我不能确定大刘的真实态度，即便前阵子他发了关注度看来不高的新闻
我个人还是比较乐观的，元宇宙由于自身发展的需求很可能自然地推动现实科技发展——它需要很多电啊！那么大推力火箭、空天飞机、核电推进、月球基地（石墨烯光伏、磁约束核聚变、无机合成营养素、月矿开采冶炼铸造）、拉格朗日点中转站（核电推进小行星捕获）、电磁轨道运输（建于月球基地和拉格朗日点中转站，配合核电推进）不就想啥有啥，人类先上个月球、火星正常吧？
还有，人玩元宇宙也会疲劳、生病（脑机接口作为最后几项之一，省下了其他部位，但脑也会疲劳），那也得发展医疗和生物技术进行人体强化乃至改造，可能身心两方面都对麻烦的太空旅行和科研更适应——要体验飙车飙飞船的快感，人需要强健的神经（从而同时有吃苦耐劳的精神）
总之，我相信人类在彻底成瘾前，足以飞出太阳系——“爷的元宇宙为啥非得和下面的地球人挤一台电脑？爷在飞船里躺平时偶尔和地球联一下机不好吗？”——已阅，可以共存
（还有，人工智能机械也可作为新势力帮人类搞航天科研——最近玩的手游crying suns）
*** 所以（这几年作为贵宾参加过国内民营航天发射仪式的——只是说我看过）大刘肯定是赢了，他引发了读者的思考——趁可能性极小的“黑暗未来”未来
*** “原来这是个文青耶”——我以前似乎把文青这个多义词想得太狭义（“细弱”“矫情”什么的）
*** 回过头来，九九读书网版本一开头的“故事背景如下”又有点看不懂了，什么版本这是？