* ((61f9fe15-3258-44bf-9af7-664f8ec2483e))
* 吾所以有大患者，为吾有身。——老子
常无欲，以观其妙。常有欲，以观其缴。——老子
* 读者你好，这里的文章只是我个人所学，不代表人类在这些方面所有用得上的成果，不意味着所有人都爱看部分或全部内容，不保证看了后都能有令人满意的收获而没有潜在的损害。
* （头上的耳、鼻和游戏里也有的心去哪了？当然是省略了——耳朵能听声音，但听嗨时晃起来机械能更大的是脑子，鼻子一般不能直接吃东西，多数人也没嗅到危险气氛的体验，心更是主要由没有思想的肌肉构成，还有一些懂的都懂的比如头发没必要再继续分）
* 器官是自带工具。器官需要休养的次序不同。观察身体/器官反馈并相应做出有利改变很重要。
* 脑
可能是无为而治、不知有之的神仙，更可能常是无事生非、火上浇油的小管理——“接着撂荒接着胀”、“接着享乐接着熬”。（从低到高的各种形态和可能的游戏等级：落日六号、鹦鹉螺号、宫殿、移动城堡、天空之城、飞船）
艺术（走进艺术世界，丰富电子娱乐体验，辅助优化兴趣结构，实现“艺术共鸣治疗”）：khtazmt：k选音影游单
读书（智者在书里，读君一本书，胜听十年话）：khtazmt：k选核心书单
* 蜕路（了解简单的原理后，是什么偷走了智人的时间精力金钱梦想呢？）：khtazmt：多巴胺的现代劫持：超常刺激vs祖传刺激
求索（功夫在书外。长期低存款的同时在生存方面多少有成长和前进的例子）：khtazmt：Walden·读《经济篇》，研究未来生存方向，室外高人，自由的代价，道德的进步，红魔k的魔鬼小屋，khtazmt：老渔夫今天告诉我命运是什么样子的（附赏析、背景）
* 实修（“流感凉双飞”等高阶健康体验和睡眠等的细节）：khtazmt：综合实修——人类精神飞翔
* 文献
分类大纲：《十类》
本文集的另一种分类方式：《活动集》
* 眼
并非观照的必要条件，但是观被照的机位，常常超负荷运转。
khtazmt：k选音影游单（偏印象）
khtazmt：k选核心书单（偏想象，逻辑中半透明的东西也是象）
* 外脑
外脑（与电子设备有关的部分。优化手机电脑的布局和设置，构建个人记录系统通过历史学习）：khtazmt：凝神——时间管理
写作（在整理后依旧凌乱的草稿堆中翻找出合适的一些复制粘贴到别的草稿或文章；语音输入可能会因为没组织好语言重来很多次吧）
* 口
聊天解闷，谈话提炼，说服妥协，吵翻冲突——皆是快意人生的重要门路。
公社（轻松愉快的伙伴和住房生活）：khtazmt：海鲜公社——青年的第二家庭
* 胃
消化囊，可能会因权限不够高而被塞进过量食物让全身一起遭殃——“你胃胀了干我们脑眼口甚事？”
饮食：khtazmt：原始饮食生活指南：入门学习
* 手
人类最初和最重要的执行工具，偏对生活进行创造改造的味道。
住物（对住房常见物品的评论及选购、使用参考）：khtazmt：住房物品讲究一，khtazmt：住房物品讲究二
自制（用pvc管等自制家具等）：khtazmt：家具简单DIY
种养（一个天台供至少一栋楼吃）：khtazmt：iAVs鱼菜共生和WTF循环农业指南
* 脚
人类最初和最重要的移动工具，偏换地方过一种新生活的味道。
采猎（简单自然的快乐）：khtazmt：赶海指南
学生（大学避坑脱坑）：khtazmt：新学生手册
驾考（自动驾驶尚未成熟并普及）：khtazmt：c2驾考经验心得
游士（“定乎内外之分，辩乎荣辱之境”的城市穷游/生存）：khtazmt：筏——零房费城市生存指南
* 心
从生跳到死，快快慢慢，也算是时间的代表吗？让世界动起来。人要健身，必先心跳。维持世界的表皮。
k自在活动时间表
健身（通过日常护理、运动、静修等发展和保持身体整体和各部位的健康）：khtazmt：随时随地健身体系
* 两性
戒淫（控制过度自慰等有害现象。“纵欲并非源于快乐，而是源于苦闷。”）：khtazmt：戒撸圣手
合爱（双修，体验更妙的性爱）：khtazmt：合爱宝典
* 皮
保护用于理解世界的世界的内在；多功能的可再生生物雨披或防水套，部分种类及/或其附属物如绒毛可保暖、活物可抚摸、罗非鱼皮可植皮
风水（住房的选择、空间规划、装修、内部环境改造等；白天亮夜里黑的空间，舒适空气的流转，温润甘甜的流水，香爽的泥沙花草）：khtazmt：家居环境
* 常无欲，以观其妙。常有欲，以观其徼。——老子
妙，理解，《十类》《活动集》；徼，界限，《器官集》
* （原在《更新》；以下参考惜时、顺心、语句、阶段等）
* “身体反馈”
“暴食”或所谓爱吃额外食物的起因与改进方案：可能并非跟现在的饮食有关，而是一直有这样的解闷习惯，只不过关注和改变饮食前并未有相应概念，所以没注意到之前的非正常进食。你是不是把它们整体上变得更好了呢？固定的两包薯片一瓶汽水总比胡吃饼干泡面面包好吧？
吃撑的起因和对策：撑多了习惯使然。感到撑就停下——胃之警觉/饭袋的把握/胃官/大胃的警告
对应各种过度——行为与器官的超负荷及机体自救：行动色受想行识（一个器官一个器官地整；时间是作用于器官的感觉），不要给自己造孽。如何在保险丝烧断前更快地进入恢复模式
为了完成某些事，人一般可以主动允许不平衡的存在，但短期内无法完成的事情还要很高程度的不平衡则并非明智之举
* 时间是一个相当常见的概念。
时间管理直接服务于身体（首先是自己的），管理时间意味着安排器官活动的优先顺序，如果不管理，器官们就会自行管理，大多数梦就是典型
人活着就时刻进行着各种各样的活动。活动的冲突（想学甚至想玩但是累了饿了撑了）源于机体/系统/器官任一的欲望与能力及相互之间的不协调，前者不协调通常相对容易通过后者在整体上弥补，但在变化之中，一切皆有可能。
你可能会注意到自己多次在手机还剩2%左右电时才瞥见，或是突然黑屏——你忽略了不足20%和10%的警告，好在手机只要能充电就能很快起来，然而手机和人的体质不能一概而论，人们在压力过大或诱惑过多时，很容易使自身超负荷，并且恢复比手机慢得多，如何减少在自己身体上重蹈覆辙呢？
别让当前不怎么重要的事人物收了你
* 先描述后设计：时间管理的时间表侧面可以参考先进经验，但在应用时应以描述（在描述/“复盘”中发现改进点）和统计（发现相对隐藏的改进点）开始以供设计参考，而非一开始就想设计规定
* 器官的协调
“君臣佐使”：有时即便是好看好玩的也不想再继续不一定是其本身有问题，而是你（或你的身体、潜意识等）更挂念别的事情，它已经从最优先的项目（至少）暂时掉了下来，把它们补全平衡就好了，机体的平衡源于器官的协调
容易的事优先做，如运动（随时随地）
* 兴趣的拓展、评价、淘汰