* 我玩的契机：密教模拟器之前一阵子在酷酷跑看到几次，当时觉得“卡牌游戏可能太复杂”就没下。过了几个月，某晚（看截图是2021.2.6）某群讨论两性话题，我终于复制了《蜜藕》的一节作为一个“清单”分享，分享前临时改一下，把一个词（可能是“功名”，把它拆成“名誉”和“功业”了——“至人无己，神人无功，圣人无名”，功和名不一定不可分割）改成了“功业”，（“必也正名乎”）搜索词义确认时又看到这游戏含“功业”（还有“飞升”，我心里嘀咕这游戏不得了/滑稽；从一个感兴趣的局部切入真的精巧有趣的整体，值）的wiki，决定玩。当然，拖了几天，2021.2.15正月初四下午才开始玩。
* “决定玩”的原因：除了春节在家解闷外，我是为了自身、写作、社团（在unciv的国王与mindustry的元帅之外，我还要做个“小企业”的教主）等方面的需要（跟实修倒没什么关系）把它当方便、集中、触类旁通的概念系统（老NT——概念主义者了/滑稽）和文学作品欣赏学习的。（文学作品：类似的游戏还有unciv，都是格言较为丰富的游戏——可以看看“技能：学识初显”的介绍。此外，把握基本套路后，除了飞升的单局目标，更多是丰富的叙事、世界观、背景故事等留住了我——研习诸史之人）
还有“学英语”（临时决定，多耗很多时间；断续的老传统了，可以朗诵、查词。不建议没有CET6以上英语水平的玩家在手机上边玩边查）。
* 基本评价
“桌游”，一张发展密教的牌桌需要控制的卡牌不是很多，没有unciv复杂，更别提p社游戏了。游戏内容丰富（不易经由重复感到厌倦和畏惧；背景故事比较吸引人），结构不太复杂（卡牌的数值大小适中，对数值差异的关注要求不高，一般熟悉后能够一眼看个大概，而没有很多需要挨个过目的套娃），卡牌到位迅速（除了部分动作需要分阶段加入更多卡牌外，基本没有需要费力盯着的运输过程；大多数行动和行动的一阶段不超过60秒），能够相对舒适地玩下去。而且是有“传承”机制和感情的游戏（有遗产legacy，且比《王权：女王陛下》更具连续性和稳定性，不容易让玩家在不看攻略的情况下反复“摇号”到“盖亚！——卢本伟.gif”）。

--------------------------------------------------------------------------------
* 参考资料
** 强烈建议先失败或小胜三次再决定是否看任何资料，以免玩游戏的“激情”丧失（“漫宿不会还有输不起的长生者吧？”）
:PROPERTIES:
:heading: true
:END:
** 百科（比教程更多自己查）
*** [[https://cultist.huijiwiki.com/wiki/%E9%A6%96%E9%A1%B5#][密教模拟器中文维基]]
** 教程
*** [[https://tieba.baidu.com/p/7068050441][【小技巧整合】密教模拟器本体日常问题、赚钱、消邪名和其他技巧]]
*** [[https://tieba.baidu.com/p/6408049144][密教模拟器资料汇总]]
*** [[https://www.bigfunapp.cn/post/133429][《密教模拟器》全！方！位！大型游玩指南[上篇]]]
** 攻略
*** [[https://tieba.baidu.com/p/7049872297][【速通指南】密教模拟器有志青年至使徒速通流程]]
* 保护视力：手机屏幕和键盘小，阅读、查询（尤其是“学英语”）不便，容易使“健康”过度“疲劳”（眼睛有没有红肿呢？），建议玩电脑版，或者用更大的显示器和键盘，或者至少设置高对比度。
* 游戏主菜单和文字前：闪过一张蓝色的画，而第一代在医院老人死去的那一晚梦到了钴蓝色的场景，即漫宿。
* “漫宿mansus无墙”：是人人只要条件合适都可以去的地方，人人皆可成仙。（当然，条件就是墙）
* 活动框与卡牌槽：活动框代表活动，默认有一个卡牌槽输入和输出卡牌。一个卡牌槽一开始会提供两张卡牌。点击卡牌槽会在右上角显示卡牌介绍和可输入性相、在牌桌显示当前可输入卡牌。进一步的卡牌槽在时间结束前输入卡牌即可，这一点帮助更好地分配卡牌。右下角会固定输出相应卡牌，右上角若有则在下一轮输出提前知道数量的未知卡牌。
磁吸槽会很快吸入当前有的未被行动锁定或手动拖住的相应卡牌并锁定。
钢笔（“契约”）槽的卡牌会被消耗。
输入磁吸卡牌槽或进入下一阶段的卡牌会被锁定，可以用来暂存一些雇佣、负面卡牌（但要注意例如画画除了重新输出外还可以制造更多同类卡牌）等。
部分卡牌的输入会以行动框为中心显示特殊画面，想看可以先把行动框拖到空地。（也要记得“大场面”前存档的好习惯）
* 卡牌：拖动卡牌，可输入的卡牌槽会亮。手机版点击一叠牌的右下角可整体移动。双击卡牌会使其自动进入系统优先可输入动作框。很多卡牌的性相和内容物可通过颜色判别。
* 卡牌保鲜
谈话：苏洛恰那、召唤物（灯的衍生胜利搭配：囚犯或特蕾莎和爱人行尸）。
其他：工作（注意公司董事旷工相当于吸邪名，并且100％降待遇）、探索、长生者
* 理牌：动作框和卡牌不该杂乱无章，否则有可能一些没注意到的负面卡牌时节一到就把你做掉了，负面卡牌要和相对应的抵消卡牌放一起。
* 作画
** 画司辰
*** 用相应性相的颜料
*** 灵感要带相应性相，不一定要密传，追随者的性相也行
* 教团的作用
** 主要是升级教徒让他们做事，不同的教团对不同的人而言升级体验不一。欲望与教团不一可能是初期研究或入梦时赶时间把同一密传和欲望分开用了不同的，问题不大，飞升条件看欲望性相点数，活物除了欲望性相的大徒弟外还可靠召唤。
*** 招募特立独行者（捣乱分子等，都要先把同等级的重复本/即秘史地点让ta吸两次变成形成途中的长生者再招募）要送工具
* 不懂就会作的常见死法
** 与负面时节有关的卡牌
*** 躁动（野心勃发的时节，在欲望性相小于3时未满足欲望升级条件则输出。60秒后变为180秒的恐惧。新手一般用激情基础作画教会加入新教徒或教徒升级消耗）
*** 恐惧（恐惧链：冬的更高阶影响~~~冬的2阶影响~躁动～恐惧～分裂出全新的可以继续分裂的恐惧）
*** 入迷（与恐惧或一瞬追忆入梦）
*** 邪名（首先，秘氛一般不可避免、不必避免，其次，线索槽读条结束变成证据槽就不会吸邪名了。与熟人谈话、探索藏宝地后输出。总部打下位于首都的藏宝地后搬家消除1邪名，与心教徒谈话概率消除1声名。多用密传谈话招熟人或交委托或画画多造秘氛，拖住单一邪名，暂停后可以放下，继续前拿起，基本不耽误别的活动）
**** 中后期有心蛾刃的门徒后别怕邪名，想画多少画多少
**** [[https://thenerdstash.com/cultist-simulators-alexis-kennedy-accused-of-abusive-behavior-by-multiple-women/][Cultist Simulator's Alexis Kennedy Accused of Abusive Behavior]]
** 把疾病放入招募
*** 会吃掉疾病，顺带把生命也吃掉。（大概不常见）
* 可玩点
** 工作和作画同时增能力牌、升技能（以及吊着猎人）就很有意思，人喜欢能力增长
* 我的游戏体验
** 第一局死亡
有志青年。灯欲史教。对手侦探拿到了初步证据，但绝望框积累的3恐惧才是杀死我的唯一原因。当时刚出来时，如果我抑制住目的尚不明确的发展和探索的欲望而去凑满足，应该还能活很久。
** 第二局
三个职业中选的医生（主要借由自己爱事无巨细地记录病人的语言的习惯获得某种遗产legacy；“我的遗产会是什么？文献？”）。灯欲启教。前期遇到一次幻象，问题不大。总部搬家消掉一次邪名，但后来为了手动拖住邪名（“拖，就硬拖。”——芜湖大司马；猎人最好不要拖，如果不只一张声名，就会加一特殊猎人）防吸差点。整体上，先多读书再入梦拿密传同时招人探图应该更快。
** 第三局
神示使徒，继承第二局的部分卡牌，第二局教主作为导师偶尔有相关活动。多一敌对长生者阻挠。
** 第四局
** 第五局
* “这游戏不合理，让我们承认这一点”（“雷鸣的秘密”）：主角能在做梦的同时上班、看书、探索、谈话等。[[https://tieba.baidu.com/p/7225101290][萌新感觉你游法术学来没什么用]]
** “教主是一位有reputation的nice guy，月均二十八九天在institute工作救死扶伤，坚持带病上班，学习正在消亡的古代语言，翻译研读古代书籍并撰写相关论文，创办并管理小创业考古公司，培训员工并发展其人生理想，指导员工不辞辛苦考察古代遗迹，积极维护公共关系，就连每天做梦都坚持上下而求索，在梦中开拓人类通往永生的道路……OMG！你有ta一半努力吗？”
* 有趣的cupboard：建教后，谈话里HQ是整人的地方，第二槽显示cupboard，可以把信徒拖进去囚禁……“A skeleton in the cupboard”（老新概念英语了），写时才想起来；之后又搜了下，也有“（小）密室”的意思，算是一语双关吧。（玩的过程中语言不要切换，游戏是这么建议的）
* 外语半天从入门到精通，教主的语言天赋便是赵元任也比不得。
* “接近蜘蛛之门”的文本让我联想到《沙丘》和书中的弗里曼人。
* 浪游旅人拿着相机到处拍，也许不只是好景色，还有一些致命的证据，她可能是司辰的猎人吗？
* 《铸、灯：一次简短的讨论》