* 新星计划培训是将近年入职、大多同龄、未来有望成为中泰的中流砥柱的新员工从全国各地组织到一地进行个人努力、同事协作、客户服务等方面的发展的培训活动，其中，作为本届新增的主要培训载体的军训，最直观的是通过体力和纪律考验的方式培养学员向着中泰共同目标努力团结工作的精神和能力，而另一方面，长达两周的培训也为同事间的较充分社交创造了条件。
* 关于军训、社交等内容，我想像24日晚集体观看的电影《大阅兵》里的吕纯一样坦率地报告我有关适应军训的经验、享受培训的体验和优化培训的建议，感谢公司的悉心栽培，希望我们的新星计划培训越办越好、一届胜过一届。
* 一、体能
** 物质决定意识，健全的精神寓于健康的体魄。
** 军训需要一定的身体基础，如果没有健身基础生病、受伤，加之可能的睡眠不足、伙食可能没平常吃的合胃口，很难不影响当代年轻人的情绪，人是
** 据我观察猜测，整体上体质应该是前台略优于后台（但部分有健身习惯的后台会超过很多前台），后台优于中台（IT岗等）。
** 在学员的体能方面，我主要想到的是健身习惯、抓紧训练、训后恢复和鞋子。
** 为避免受伤，也为了能够有更好的表现、得到更充分的训练和各方面更积极的体验（健身可改善，也能避免很大一部分，绝大多数人受伤时不会有多喜悦的），建议学员们在军训前就养成健身习惯、积累健身基础（如翻轮胎需要正确硬拉的基础），一两分钟休息时间即可完成一组自重或重量训练，每天运动十到二十分钟即可。
** 以后军训或可组织学员提前半个月以上在相应微信群内开始每日健身分享（包括健身资料的分享：个人推荐囚徒健身和八部金刚功）、打卡等。
** “凡杀不死我的，必使我更强大”
*** 如果学员已经在军训了，并且平时没长途走跑的习惯，则要在长途拉练前抓紧时间充分训练，“早练早酸早提升”，尽快提升腿部的乳酸耐受能力，以免拉练后几天肌肉过于酸痛影响出勤——但训练十天后，不到十公里就走不动的同事仍不在少数，所以平时的健身习惯仍更优先。
** 训后建议尽快通过拉伸、按摩（器械有泡沫轴、筋膜枪、筋膜球等，很多可以共用；没有器械也可用拳头捶打或把小腿硌在膝盖上抖动按摩）等加快缓解疲劳、消除酸痛，在剧烈运动（冲刺跑、篮球赛等）前适度拉伸热身也能减小受伤请假的概率。
** 影响训练的物品主要是胶底作训鞋，它的主要优点是迷彩与衣服裤子风格统一，但它相比常见的eva底的运动鞋的缺点则是容易在前部挤脚、胶底硬/缓冲差，比较费力、内部也粗硬，容易阻碍足部血液循环、导致肌肉肌腱紧张过快疲劳乃至挤伤磨伤脚趾，建议以后采用新式作训鞋以减少不必要的劳损受伤（尤其是正步可能伤脚踝），或者可以配对气垫鞋垫，但那样垫高脚底通常需要较大的鞋码
* 二、思想和心态
** “态度决定一切”
*** 首先要抛开“我是过来受苦影响工作进度”之类不切实际的想法（这也有助在客户面前表现得不卑不亢、宠辱不惊，如果我们暂时不会挖掘客户的独特点，也至少别感到厌恶）
**** 军训留给多数岗位处理重要工作的时间是足够的
**** 军训内容比较丰富，比绝大多数中学大学军训有趣多了
**** 教官也比较和蔼，不像初高中军训那么严
**** 几乎所有人都能在这么多同事中交到有意思的好朋友，这些好朋友也能帮助提升对工作的认识，很多同事因为疫情等原因来不了还惋惜、羡慕呢，甚至有不少同事还觉得相见恨晚（可能晚上和老乡聊得都不想睡觉）、时间不够聊、同城的同事训后还要再吃几次饭继续聊，中途因为基金考试还提前合影，最后一两天依依惜别——所以有什么苦呢？
*** 事后我们会发现，这是我们这批年轻人的一段难忘的经历。
** 将“惩罚”加工为自身成就
*** 了解尼采的人大概知道“精神三变”（骆驼“你应该”，狮子“我要”，婴儿“我是”），这是一种混合的状态，我的确在，我要
*** 有时教官因为自己、同排或不同排的其他同事表现不好或单纯按训练计划而让我们站军姿、做俯卧撑等，为了更好地完成这类相对费力的活动，我们可以将他人“惩罚”“折磨”我们、可能引发明显或隐蔽的对抗性的意图（即便教官可能真的是这么想的）“拿来”，转化升华为属于自己的超越性动机（什么都不想只管做也可能，但大概更难），例如可以为了矫正体态（现代人多少有体态问题，而站军姿总共不过几小时就能让身材明显挺拔起来，穿司服也更帅气美丽）、锻炼或挑战证明自我的能力而为自己服从，挑战证明自我的能力就像电子游戏有提升用户粘性的丰富的成就系统，军训中同样可以有内生成就——（“教官让我们站军姿是罚我们来着”可转化为“既然不说身体不适就肯定要站军姿，那么我能不能站军姿半小时或更久呢？能不能少抖点”有了这样的目标，站军姿就容易了——“工作亦然”——当然，这样的成就系统一般还是需要健身基础和习惯作支撑，同时也需要日记习惯，看自己是否重视这些小事和不一定能用上的信息
** 直面错误
*** “人恒过，然后能改”——训练时动作做得不好很正常，不要图省事或不好意思大声喊“报告”，对自己敷衍可能对本来很快能学会的技术产生畏难乃至摆烂的心理从而拖很久还学不好，只有正视而不是隐瞒自己的错误，才能有决心和动力更快地发现错误所在并改正。
* 三、精神
** 榜样、模范、英雄的作用很重要，例如此期的国防知识PPT讲座、战斗英雄口述故事，如果事先对人物、事件有个相对详细的简介（例如这次靳教授比较谦虚，没把自己身份、级别说得详细，没能充分激起人对权威的敬重心理，而王刚老战士在叙述中才慢慢展开时而跳回之前的时间线做点补充说明的介绍，一开始不注意记录的话几乎不可能记住故事高潮之外的重要细节），学员就可能更加重视、更用心听和做笔记，这样就比让学员全靠自觉专注到底、努力悟更好，电影等教学材料亦然。
** 另外，为避免可能一时想不出较有价值的提问，也可提前让学员准备问题。
* 四、社交
** 多听，多说，这里人才很多，军训外的时间不能也很难独自窝着玩手机浪费掉。
** 或许可以说，学员间的社交是维持军训得以正常进行的最重要保障（或最主要的保健因素）。
** 面对面交流
*** 我们一般会利用训练休息、用餐（我们这桌叫“圆桌会议”，第一天午餐举酸奶干杯后就这么定了下来，成员“圆桌骑士”有二排长、三班长、因脚伤和才艺负责摄影宣传文稿晚会筹备画风筝上的山水画的文青、二排参加篮球赛的主要队员，还有我这位闲着找事做、时而到处听听问点问题记笔记的，这么一桌人这么一坐，经常就是一桌欢声笑语；想想看，我们和相同客户一周能吃几次饭呢？和参与新星培训的同事，则是一天三顿，频率高过同事、家人和曾经的同学）和宿舍休息时间，面对面（高效，而不是在网上慢慢打字发语音）、亲近（同龄人很容易拉近距离）地聊天（相对偶尔因为异地业务联系而公事公办），然后能发现不少在某方面有两把刷子的人才，甚至旁听都可能选择困难——不光是工作内容，各自工作前的经历也很有意思，而且后者的分享本身也利于有关工作的眼界拓宽（如不同部门岗位关于市场研究理念的分歧交流）和业务协同——有些人才甚至聊到了吸引邻居多次串门旁听的程度。
*** 绝大多数人都会和其他同事聊天，但可能岗位之间由于工作性质（是频繁接触陌生人还是程序代码）而存在差异
** 指挥、演讲、表演
*** 小范围的深度交流能迅速增进情谊、增长见识、增强对集体的责任心和荣誉感（进而也能帮助自身和所在集体提升军训表现），面向数十上百人的演讲则能显著提升自信，同时也是锻炼积极主动推进集体工作任务（例如营业部开会讨论销售计划）和未来管理者应掌握的基本技能。
*** 广义上，学员在培训期间在众人面前发表有准备讲话的行动，按大致的参与度、难度综合升序有：动作要领讲解（每个人都讲解，如“齐步的行进与立定”）、军训指挥（每个人都指挥）、喊“报告”（虽然简短，但多次喊客观上也能引起大伙儿的注意和熟悉；擒敌拳喊的“哈”也算）、领唱司歌军歌（如在学司歌时脱颖而出的文艺委员）、节目表演、每日心得分享（如参观坊子炭矿博物馆和坊子博物馆的）等。
** （一）社交方面的建议
*** 这些自发程度不一的活动已较丰富，但似乎仍有不少增加热度、深度等的余地——“如何让学员通过初期有引导的正面反馈爱上正面、主动的自我表现”是个很有价值的问题，优化这个进程就相当于加速“破冰烧水”、“从零到一、从一到多、从十到百”，从而有效地加速学员进入状态、熟悉同事、融入集体、充分表现。
*** 例如自我介绍，之前的自我介绍可能因为在军训氛围下进行，一般比较简短，如果准备相应的参考模板应该会更好，比如一般可以有细化到爱听的歌手音乐风格之类的爱好、家乡的美食景区特产等。