* ((636a40a9-1ab6-4d29-835a-f8d8bd2f4e06))
* 相亲会吧？不会可以让我这个没相亲过的教你，首先和正常社交一样，不要搞什么违法犯罪和下三滥
* 相亲的特殊性
** 人没几个朋友也可能过得不错，但要相亲就是不一样
* 思维
** “什么男人不能说不行！男人承认自己不行不行吗？”
*** 不要让传统观念束缚头脑手脚，男女平等也包括不再要求男性当顶梁柱苦钱养家
*
* 门当户对
** 门当户对，到底是什么门、当、户、对？
** 为什么门当互对会被默认为更有优势？
** 要拓展和改进
*** 我希望我们能走段精彩的路，而不问远方终点为何
保持独立性（一般不超过跟着吃席的程度）
* 额外补充
** “年轻人不讲武德”
*** 老相亲短平快，一点都不2021，不妨先从探寻人性之类的角度出发认识和发展相亲者，如果结果不佳，我觉得过程之复杂冗长也能让亲戚知难而退
*** 传统相亲是一种对关系的浪费，毕竟人际关系是多元的，而相亲通常只要一种结果的有无，之后便抛之一边
*** 好比好不容易跑到菜场只想买一个菜，没有还看不上别的甚至可能更好吃的菜
*** 相亲是种特定的框架吗？如果你和网友关系不错，为什么不试试和他们走这个框架
*** 重要性排序及评分比例
**** 思维
***** 理解我目前虽渺小但对我重要的写作及其相关实践内容的重要性
***** 人格
****** 不太幼稚
****** 不说乐观开朗、处变不惊，至少不太抑郁
**** 财务
***** 有自己的购物实验计划，把生活花出花样
**** 健身
***** 有自己对仪容仪表的讲究
** 相亲平台
:PROPERTIES:
:id: 610fb928-4c35-43b1-a56d-83000f98ba65
:END:
*** 如果你是差不多像我这样的人（我指的是经济地位和生活态度），那你突发奇想去研究，为什么要相信“万中无一”的自己能看到一面差不多的镜子呢？说偏颇点，“哪个正经人玩这APP？”大海捞针有可能，但没必要
* 从本群的字面意思开始。（“相亲相爱一家人？”）
* 一个群与个人的整个社交结构
** 一个群的性质很难完全被群名称本身限制（本群实际主要是闲聊/约饭/交友群，直接相亲的属性不太明显），即便一心紧贴“相亲”标签，事实的相亲也很难一蹴而就。个人的整个社交结构（不同个人、不同阶段之间显然有差异）的平稳发展往往需要多方面的配合，所以先用“原食”、“吃肉”这样的标签“交个朋友”往往是明智之举。
* 比较优势与自由全面发展
** 盘算相亲大事当目光长远，一个人只具有少数几方面的比较优势（“能和大家一起愉快地吃肉算吗？”）的话，可能“比较乏味”、不足以较全面地维持较高水平的亲密关系，如果为了这样的目的，就更要注重自由全面发展。“全面”不等于“全都要”，如果能做到大幅消解忧虑恐惧等负面情绪（包括在没有忙相亲的具体工作时为相亲担忧犯愁这类情绪），这样的群友就已经赢了。
* 具体项目
:PROPERTIES:
:heading: true
:END:
* 线上相亲名片
** 本群多数相亲者用的是“相亲名片”小程序
* 自我介绍
** 社交卡片、简报等形式，相比“相亲名片”更一般化，不一定给别人看，可以当镜子用，发掘自身优势。格式自定，以下条目（文档里一般竖着排）内容均为选填。
*** 社交卡片设计（可翻的：照片之外的其他内容可筛选突出，而不是只突出照片等）
*** 兴趣（包括饮食、政经等）、互助、交友、相亲
*** 健思社行
*** 体测数据（耐力、爆发力、灵活柔韧等；基金测序等）/爱好特长（艺术类：听音乐、乐器、歌唱等，任选三到五首点评，“更多详见”）/外貌声音（外貌、歌声像什么明星）、mbti/大五人格/项目分数、收入（收入低就不要为己啦？）/大致人脉（家庭出身等，可后置）、旅行（在哪生活过上过学去过哪玩等，包括本地，包括剧本杀、游乐园、展会、音乐节等）
*** 生活方式（计时，可后置）
*** 基本（一种格式：姓，性别，出生年，常住省市区；外貌方面，照片考虑隐私和设备技术条件一般不公开，身高体重等可能太抽象没多大价值也可以不写）、人格（推荐大五人格，其他可选，可附测试报告链接，有归属争议的可以再做一份新鲜的，或者不管）、财务（可以有收入、支出、行业、岗位等；可以不展示，就“交个朋友”而言似乎不是很重要）
*** 常见艺术爱好（音乐、影视、游戏等，可附相关的个人主页等链接）、其他爱好（阅读、运动、美食、撸猫、户外等）——具体点描述自己现在和过去（毕竟很多爱好的享受较快，然后就至少暂时成为过去了）是怎样享受生活的，除了发现或发展可能的同好外，会享受的人一般对自己和他人都不会是太大的麻烦
自我评价、社交偏好
*** 本地推荐去处（如果线下会面/聚会，优先考虑去哪旅游、采猎、聚餐等——方便线下会面/聚会直接获取意见；如果当导游，最好先体验一下当地导游材料，当然，有面子或不想重复学习也可以到时候再听）
*** 什么时候有用：网上信息容易不完全、不对称，更有效的还是线下会面，社交卡片的内容也可以见面后且有需要时再抖出来。
* 闲聊
** 进群和进群后的心态：可能不少群友相当程度上是出于好奇或看热闹图一乐的心态顺手进了群，可能不少群友还没怎么了解过有关相亲/亲密关系、原始饮食等的知识，但这些不太重要，毕竟本群的确很简单，群主一如既往没给什么群规和指导说明（大概是这样？），本群的用处是我们自己发现的。这里还没有面试，群友们不必为自己的想象感到紧张。
** 进群渠道对本群内容的影响：部分群友可能因为之前的渠道比较散乱等原因，对原始饮食等理念本身的新鲜劲（有些不懂宗教的人会叫它“宗教情绪”）还没过——关于饮食这样的常见话题，老同志可以用这样一些理论紧密结合实践的车轱辘话作卑微的总结：“怎么吃舒服怎么吃”、“一般情况下不必迷失在正反研究和意见堆里，一切食物当前对你的好坏取决于你的身体反馈”、“有未记录反馈的食物补剂等记下反馈寻找规律照做，心知肚明熟悉了就可以不记录了”。
* 学习
** 反面教材
*** 有时（曾经，可能别的群还有）会发现整体上还不错一个人，表现欲旺盛本身问题不大，但放不下取悦和维护自己的“核心价值观”或不必要的自尊的习惯，没有尊重客观规律，乱说骚话（很多是大家能够理解但不一定喜欢的话，而且不是什么了不起的原创）、乱用表情（除了可能也包括年轻人常用的狗头等，面具戴久就难摘了），然后可能被看不顺眼、选择性无视、和别人杠起来乃至被请出去，这样很可能失去（继续）互相学习的机会。
** 阅读
*** 《幸福之路》（罗素），相亲本质上应该是为了幸福；《亲密关系》（罗兰·米勒），了解有关亲密关系的知识。
* 线下会面/聚会
:PROPERTIES:
:id: 606466bb-24bd-49c5-bfcf-0089efd8655e
:END:
** 可能是最实在的部分，就交友而言，线下会面/聚会比线上群聊私聊要广泛（能被更多人接受；人多也“热闹”、“性价比高”）、准确（相对难造假）、快捷（说话一般比打字快，各种语言和非语言信息传递迅速）得多，有助于形成更合理的心理预期。
** 形式
:PROPERTIES:
:id: 60647953-4ad2-438e-b333-d1b885c4938a
:END:
*** 面谈
*** 健身（移动空间：散步、跑步、自行车、摩托车等陆地运动，游泳、皮划艇等水上运动，跳伞、滑翔伞、三角翼等空中运动；器材来源：自然、建筑、团体；器材自由度：羽毛球、乒乓球、网球等球类运动，弓箭等射击运动，VR健身游戏、哑铃、壶铃、杠铃等自由器械运动，滑梯秋千跷跷板、健身公园、健身房等固定器械运动；目的：广播体操、金刚长寿功、普拉提、瑜伽、冥想等保健运动，采摘蔬果、钓鱼、赶海等采猎运动）
*** 旅游（公园绿地，自然景观，游乐设施，线下解谜、电影院、剧院、图书馆、博物馆、美术馆、文化/记忆遗产等文化场所，商业街、超市、菜场等购物场所）
*** 聚餐（蒸、涮、炖、煎、烤等；较高频率的聚餐考虑各人经济条件不同，可以准备多种多档食材，餐费AA或有钱请，场地可以是合适的餐馆、农庄、户外、办公场所、体面住宅等，有相关聚餐经验者可以多指导）
** 总之，丰富多彩，很多人宅着不参与这些活动可能主要是觉得没人陪着还没和手机玩有趣。其实想想看，相亲的同时顺带做好多平时不愿做但认可其益处的事，这不稳赚不赔么？很多人是只要有别人陪着共同参与就感觉不错，甚至不用说多少话，完全不费事。打开随便一款地图或旅游软件，多种多样的去处随便挑。
** 可能的效果：一起买省钱、趁新鲜吃，没冰箱和独自做着吃不方便的人（住校生、下班晚等）每次聚餐能多吃一两顿肉并可能带回去可吃若干天的可常温保存食材（浸没在水里的黄油、精炼油，罐头、真空包装食品、腌/干制品、蛋、其他乳制品，海藻，淡水鱼等活鲜），切磋厨艺，拓展人脉和市场（群友可能是潜在客户），拓宽眼界和道路（看到世界的更多侧面，把自己本想做但没做或不方便做的觉得有趣的事介绍给别人做）......
** 昵称加城市：加在哪都行，都能搜到，但是城市放前面可能在“查看全部群成员”里不能直接看到昵称）。方便搜到同城群友、摸请本群大概分布和比例。
** 城际：（如果同城活动还不够有趣）不同城市可轮流举办，在疫情问题不大的情况下一年至少能办十次，有些人出差都不止这个数。
** 线下聚会对这个群的影响：爱看闲聊的群友担心衍生的聚会群把这个群分割是无益的，这个群没有指标，如果线上线下都没被捎带上，可能自己就要主动点。
* 有关集体成就的小目标
** “文化胜利”（可选任务，参考游戏文明系列和unciv；悲观地看还可以有“存活胜利”——最后一个“死群”）
*** “其他三个群可能需要我们的协助和指导”（也许事实的确如此）——对集体荣誉的过分热忱（？）也许会引起一些麻烦，但时间独自浪费也是浪费。群友们有闲有心情可以分享自觉有价值的东西。