* “不亚于[[音乐分类评论]]的素材库限时免费啦！”
* 名言的作用——认同这些语句的话，留言者们会一起推动你。
* 问题
:PROPERTIES:
:collapsed: true
:END:
** 分类
** 过度冗余（之后有更简洁明了的，所以是白费力气？）
* 健身
:PROPERTIES:
:heading: true
:END:
** 护理
** 静修
*** 睡眠
**** 梦
***** 梦是对人类必须入睡的补偿吗？
** 实修
*** 《我说参同契》
**** 由来富贵原如梦，未有神仙不读书。——舒位
**** 此身未有神仙骨，纵遇真仙莫浪求。——？
** 运动
*** 意义
**** 运动的意义不是数字，而是维护和发展使自己快乐（至少不至于不快）的身体机能，具体形式服务于这一目标
*** 游戏/快乐的运动
**** 在负反馈之外，还有快乐时或有明确预期的快乐前的更自然的运动，例如听着音乐扭起来转起来、和爱侣合爱、愉快地交替单脚跳
*** 冲凉
**** 在暖和和懒惰之间，我选择靠我更近的（注：豹豹群发言，“更近”可看出三种意思，一是当我在浴室临冲澡时，没开的热水器在厨房，二是“我”字更靠“懒惰”，三是豹豹看出来的，从他的视角看，群聊中我的头像其实靠“暖和”更近）
*** 跳舞
**** 自然而然的，那些同样听到音乐的人也基本跳不起来
** 目的
*** 减肥
**** 为什么减肥：为什么会成为一个流行方向？抛开商业因素，不顾自然的性吸引力的瘦身文化是否也可能由于个体对人口密度等社会环境条件的觉察？
**** 减肥通常难的原因：减肥很难，难在很快新的正面反馈就少到可怜了，如果能持续获得正面反馈，为减肥所做的事就会成为习惯而不必想着要执行。
本身不是自己很想做的事，很难提供持续反馈，而那些能够持续提供即时反馈的事则会赢得竞争渗透进来，把好不容易冒出来的一点哪怕只是自己“选择”做某“更好”的事的“意志”给撕裂，继续做断线风筝。
所以要把那些破坏“意志”的事情给请出去，而把减肥和健康学习赚钱等团结起来，只有融入一个完善的系统，减肥本身才容易成为本能[抱拳][奸笑]——施生朋友圈评论
**** 减不下去的原因：那你可能需要先解决喝酒和睡眠不足的问题，很多人以为自己能接受拆东墙补西墙时并没有意识到自己拆的其实是承重墙、减肥者算不准原理（注：指热量）
**** “缘分”：吃时不用想那么多，认真吃，体验食物的味道，因为这是食物和你的缘分，吃后还可以客观记录。平时可以打坐
**** 标准的秤和不标准的自然
***** 秤是压力源：没有重力的世界，哥们不懂？秤也是压力源，还占地方，不参加比赛干嘛踩它？ 选了错误的目标作为主要的目标，当然会有各种各样的障碍，如果选择让自己更开心，那直接把秤去掉就行，大概
***** 脆弱的压力系统要维持这个脆弱的压力系统的存续甚至良好运行，人类需要环环相扣，可能一两个秤坏了这个系统就会崩塌
***** 往秤上一站，压力或奖赏立刻反馈，但它的活路和死路就一条，改变方向的余地很小，好像总是要面对同一场考试；往船上一站，无情的大自然淹没了人类虚无缥缈的内生压力，它的活路和死路都有很多条
***** 也许越亲近自然的运动越不会引发秤的压力和制造作为机器一部分的人
***** 秤是万物的尺度
***** 你心中还是有秤
***** 就为了让秤的数据轻一些，把那些比较轻但珍贵的东西丢掉，这样值吗？
***** 不能因为沉迷于一件事而不去思考其他可能重要的事，否则哪怕是最有益的一件事，实行起来也会和“减肥”没啥区别
***** 更何况“减肥”就是很多人认为最有益的事，体重秤就是频频立于其上者的理想监狱
***** 体重秤是装了放假新闻的电视的单人牢房
***** 囚犯们穷到只有体重
***** 自然被秤们忽略了，因为它称不了
***** “饭袋”的心理原因和生理基础：“饭好了，我应该吃，虽然现在还不饿，但是也不算太饱，食物的美味令人愉悦，现在就吃，早吃早结束”——尽管之后可能吃撑，然后到了晚上觉得之后可能还会饿就继续撑——一般而言，人的消化系统及相应本能似乎更发达，使我们更容易在这些方面犯更多的错
***** 暴食：干不掉老板，干不掉客户，干不掉房子，干不掉……但吃喝是可以明确地干掉的，暂时
** 人
*** 人是大地的触须。
** 健康
*** 健全的精神寓于强健的体魄。
*** 很多收益不是钱，此外，如果采取较高的标准的话，很多钱实为对其他方面的补偿，而且一般还是打折的。
*** The only way to keep your health is to eat what you don't want, drink what you don't like, and do what you'd rather not. 
:PROPERTIES:
:id: 621d9b0f-a8fd-433c-b814-b34b520d0f1e
:END:
保持身体健康的唯一办法，就是吃点你不想吃的，喝点你不想喝的，以及做点你不愿做的事情。——马克吐温（所以不要在另一种意义上与健康的本能背道而驰折磨考验自己，不要为这样疯狂的自己喝彩）
*** 一人饮酒醉：身边有逃不开的醉酒者要和你“讲道理”怎么办？讲道理和生气都是没用的，在他们成为麻烦前回卧室吧。
*** 醒/睡的理想状态：您的开（关）机速度打败了全国99%（100%）的用户
** 骚话
*** 像蜜蜂一样急不可待地钻进花朵吸食花蕊间分泌的花蜜（男女皆可）
*** 我是我俩的充电桩
* 思维
:PROPERTIES:
:heading: true
:END:
** 观察
*** 会听，会看，你就可以遇见美了。——克里希那穆提
*** 探寻真理之人不可心怀傲慢，不可嘲笑无法用科学解释的奇迹，不可回避这个世界的美丽。——一之濑夫妇，《CLANNAD》
*** 一旦意识不到我们是自己的主人，我们就成了危险人物。——《非暴力沟通》p22
*** 不带评论的观察是人类智力的最高形式。——克里希那穆提，p29
*** 冥想，就是将心智从已知中解放。——克里希那穆提
*** 清空心智就是冥想。——同上
*** 充满光的心灵不追寻。——同上
*** 自我意识——物中现象
** 情感
*** 激情
**** 在隆冬，我终于知道，我身上有一个不可战胜的夏天。——加缪
:PROPERTIES:
:id: 64631f13-bc63-4482-a512-9405eed8d911
:END:
*** 易/“无常”：一日之内，一宫之间，而气候不齐。——《阿房宫赋》
:PROPERTIES:
:id: 6437d194-a29a-4401-ab0c-06482df22aab
:END:
*** debug：全都拿出来看看，怕什么呢？怕就拿出来看看。掏空就轻松了。拿到外面，排好，在外面观赏和享受。
*** 社会
**** 社会经验：社会很大，你说的哪门子经验？
**** 荣辱：定乎内外之分，辩乎荣辱之境。——《庄子·逍遥游》
:PROPERTIES:
:id: 62a1f190-3c83-45fd-9afb-c663c7cb15de
:END:
**** 爱
***** 我说
****** 不要总只期待着被这个世界温柔相待，那样就应该首先温柔待它
****** 自由是第1/2法则，保护人类整体是第零法则，爱是法则（重读阿西莫夫的双百人有感；注：爱是什么法则忘了，当时很晚了）
****** 情歌多？压抑。
***** 适应你命中注定的环境，爱你命中注定所要遭遇的人，而且是要真心地爱。——沉思录
***** 爱自己是终生浪漫的开始。——王尔德
***** 爱所有人，信任少数人，不负任何人——莎士比亚
***** 当爱到了终点,软弱者哭泣,精明者马上去发现另外一个,聪明的早就预备了一个。——王尔德
***** 宽容（放弃惦记别人的“伤害”）
****** 为了自己，我必须饶恕你。一个人，不能永远在胸中养着一条毒蛇；不能夜夜起身，在灵魂的园子里栽种荆棘。——王尔德
****** 我天天看各种各样的人犯各种各样的错，不也没什么感觉么？
***** 兴奋：为了避免过度的兴奋，一定量的厌烦是不可缺少的；过度的兴奋不仅有害于健康，而且会使对各种快乐的欣赏能力变得脆弱，使得广泛的机体满足为兴奋所代替，智慧被机灵所代替，美感被惊诧所代替。——罗素
***** 不服气（对憋屈现状不接受）：人活着争口气
***** 虚荣
****** There is no doubt that in exchanging a self-centered for a selfless life we gain enormously in self-esteem. The vanity of the selfless, even those who practice utmost humility, is boundless.——《狂热分子》
****** 人呢就是喜欢 发现并证明自己的了不起[呲牙]——网友
*** 傲慢：弱小和无知不是生存的障碍，傲慢才是。——《三体》
**** 真正傲慢的人是不说话的
*** 丢脸（具体、即刻的自卑）：没有任何人必须为自己感到丢脸，如果一定要有的话，那也就是那些不让自己觉得舒服的人吧
**** 丢脸的是不是“我”还有待确认
*** 嫉妒
**** 同情一个朋友的苦难是任何人都能做到的，但同情一个朋友的成功则需要具有十分出色的素质。——王尔德
**** 对于聪明人来说，他绝不会因为别人拥有自己没有的东西，就停止享受自己已有的东西。——罗素
:PROPERTIES:
:id: 6225dc31-807e-4a09-b026-493e5576a085
:END:
*** 心灰意冷
**** 一个人不哭的那一天也就是他的心变硬的那一天，而不是他的心充满欢乐的那一天。——王尔德
*** 生气
**** 生气通常只是一个人（没写完？）
*** 仁慈
**** “仁慈，”守夜人道，“仅能在影中觅得。”——不仁梵咒，《密教模拟器》
***** 所谓“仁慈”，不过是偷偷摸摸做的事。仁慈也可能在理解后感到受辱（人话：部分仁慈就是瞧不起人）
***** 唯有在影中不会被骄阳灼伤
**** 无论如何，适格之人必须心明眼亮。“我誓将己身献出，为愿者，也为不愿者点亮路途。我誓将指引前路。我誓将照明驱暗。我誓将拒绝仁慈。我将踏上已显现的路途，无论代价为何。”——提升至先见者， [[https://cultist.huijiwiki.com/wiki/%E8%BE%89%E5%85%89%E4%B9%8B%E9%95%9C][辉光之镜]]，密教模拟器
***** 仁慈翻译成怜悯可能更符合多数情况，而在少数情况中，这份仁慈本是留给自己的——先见者无使为自哀自怜（可能也有孤芳自赏）之所劫哉！
*** 勇气
**** 勇气是去了解恐惧，并且把恐惧化为我的囊中之物！——《JOJO的奇妙冒险》
**** 勇者愤怒，抽刃向更强者；怯者愤怒，却抽刃向更弱者。——鲁迅
:PROPERTIES:
:id: 62119ff1-9551-4bbd-94b7-4f38af22760b
:END:
**** 恐惧
:PROPERTIES:
:id: 62e26b65-ff8b-4aff-9b99-2c4134401bf9
:END:
***** #+BEGIN_QUOTE
恐惧是思维杀手，恐惧是引向彻底毁灭的小小死神。我将正视恐惧，任它通过我的躯体。当恐惧逝去，我会打开心眼，看清它的轨迹。恐惧所过之处，不留一物，唯我独存。——《沙丘》
#+END_QUOTE
****** [[http://5sing.kugou.com/yc/1148376.html][穿越]]
:PROPERTIES:
:id: 62e88e7f-2b99-4500-ab9e-909bc55b5325
:END:
******* #+BEGIN_QUOTE
容承已经没有绝路，只好退进河里，
只有无力从河流穿过去，离开一切。
跳河流是被逼迫的，人们无能为力。
水流得非常急，朋友们不敢一起走
过去。

现在
越是走 就越远，孤单地，想起来 以前事 不再痛。
以前因为
很害怕、很生气 就做事，而现在 这一切 再也不 引起他 做什么 事。

没有什么可失去的，再也不会害怕。
心无追动，留下空间给精神的力量。
容承飞在心镜上，不是他想做什么，
而他无法阻拦事情通过他的发生。
而且

心镜
找不到 他心里 可反射 的目的，无法把 他伤害。
而那帮派
看到了 没有人 从心镜 受阻扰，他们就 生气了 就遇到 反射力 死。
#+END_QUOTE
*** 个人
**** 独立
***** 独自能立
***** ((627ce87f-783f-4c32-8044-3a10cde81cf2))
**** 满足于贡献（做了一件大好事）：事了拂衣去，深藏身与名。——李白
**** 为自己控制不了的事情而担忧紧张，几乎是任何被认为应当具有源于此的自尊的人的必经之路。
**** 自信：一种自信，是否可能源于回避现实中的人？
**** 什么是自信？我无知，这算自信吗？
**** 思想即时间，而正是时间制造了恐惧。——克里希那穆提
**** 烦恼：人活在世上要是没了烦恼，活着还有什么意义
**** 神散（紧张焦虑、贪多求全的碎脑）：神和智一样是人的一部分、没有做什么很重要，很多人妄图吞食世界，把皮囊给撑漏甚至撑爆了
**** 强迫（贫困的完美强迫）：怕100分的卷子，10分的饮食没全对，最后60分都拿不到
**** 控制（控制欲）：不说控制的话也至少是“安排”
***** 控制“控制”很难，没有合适的持续动力，坚持就是苦役。当呼伦贝尔大草原出现在你家门口时，你就不用想着半片羊怎么吃了
:PROPERTIES:
:id: 65bcc04b-4f7d-4e75-a152-3b6b717db54e
:END:
***** 控制别人是不可能的，即便他们做出了类似动作，也可能是我们无法得知的其他原因
**** 牢骚：牢骚太盛防肠断，风物长宜放眼量。
**** 饮食洁癖（担惊受怕的饮食）：吃了没不好感觉的不能觉得不好、比评价有用的是客观地记录食物的影响
*** 价值观
**** 需求就是现实与期望之间的距离
**** 平庸普通平凡
***** 我说
****** 我们有一位非常好的朋友，有一惊世骇俗之言论，说北大人很平庸，虽然我也部分赞同，认为没有什么特别的理想的人再怎么聪明也只是聪明人罢了，摆脱不了平庸的本质，只有火热的理想能让人摆脱平庸。不过，什么是平庸呢？平就是平天下，庸就是中庸，平天下也包含平庸，平天下要用中庸的方式，中庸就是有情有理有利有节——“喜、怒、哀、乐之未发，谓之中。发而皆中节，谓之和。中也者，天下之大本也。和也者，天下之达道也。”
****** 普通可以普通，平凡可以平凡（道可道）
****** 不用挣多少钱也可以成为“普通人”（普遍通达、普适通透）
***** 不要冷漠地走入普通人——冬泳怪鸽，快手《看见》
***** Man rarely affect me as grand or beautiful，but i know there is a sunrise and sunset everyday. ——梭罗
**** 幸运与厄运
***** 幸运的好处令人向往，厄运的好处叫人惊奇。——塞内加，《培根随笔全集》
***** 你可以自信地喊出砸瓦鲁多，然而你将发现，即便世界为你停下，你依旧无法改变属于你的命运。
**** 伟大：集人的脆弱与神的旷达于一身，才是真正的伟大。——塞内加，《培根随笔全集》
**** 神
***** 神是一类理由
**** 对谋生/生活水平的态度
***** 别人为食而生存，我为生存而食。——苏格拉底
:PROPERTIES:
:id: 65d0ac86-64c9-4851-8afb-a418517c55e6
:END:
***** 君子谋道不谋食。君子忧道不忧贫。——论语
***** 子贡曰：“贫而无谄，富而无骄，何如？”子曰：“可也。未若贫而乐，富而好礼者也。”
***** 余则缊袍敝衣处其间，略无慕艳意。以中有足乐者，不知口体之奉不若人也。——送东阳马生序
***** “公允价值”，对独特的个人而言，他能忽略这种价值对自身所珍视的价值的挤出吗？
**** 有点热心的过来人
***** 是的，但看到经历我过去经历的人，我偶尔会（想）犹豫着是帮他们加速度过还是直接抄近道
***** 我们谁也忍受不了和我们同样毛病的人。——王尔德
**** 可控的错误
***** 默认错误的存在，如何让错误像疫苗一样可控就又成了一个问题
**** 普遍的功利主义是不存在的
***** 人类的悲欢可以计算，但是并不完全相通，很多情况下，我们甚至会觉得他们有些吵闹
**** 善
***** 善是唯一永远也不会亏本的投资。——梭罗
***** 有益的生活自然也是有利的。
** 人生意义
*** 未经审视的初心很危险，包容的心态既安全舒服又有竞争力，自我实现在条件成熟时不可避免。
*** 觉醒和思考：人生的最终价值在于觉醒和思考的能力，而不只在于生存。——亚里士多德
**** 思考，欲罢不能
*** 人生中不存在任何必须的事情，只存在不必要的期待。——卢安克
:PROPERTIES:
:id: 61890cd9-2863-4b18-a23c-b96c5a3a96dc
:END:
**** 我对这句话的理解是这样的：一，就比较而言，人与人的禀赋、境遇等各不相同，适合一个人做的事情无法强求另一个人同样做。二，就个人所做的事而言，可以不是“必须”而是“自然而然”、“下意识”做的。
*** 人们交口称赞和认为成功的生活，无非是生活的一种而已。我们为什么要夸耀一种，而牺牲其他各种呢？——梭罗
*** 从现在开始，你的存在不需要理由
*** 为人类活下去真是太容易了！他们改变很慢
*** 时不时离开（“舒适”到）难受（的）区出去散个步，就会发现世上值得做的事还是蛮多的
*** 越聪慧的人群中越能凭其聪慧应付这个世界的无意义的人的比例越高，因为仅凭很少“实效”地运用那样的聪慧便足以收获很多满足感
*** “不能听命于自己者，就要受命于他人。”人类备受别人的事折磨的一个重要原因是哪怕在闲暇时也没有充足的自己的事可做，无聊招致不必要的损害。
*** 生命中最难的阶段不是没有人懂你，而是你不懂你自己。——尼采
:PROPERTIES:
:id: 62413092-2801-4c46-b4b6-7452682b4f1e
:END:
*** 人最宝贵的是生命，生命每人只有一次，人的一生应当这样度过：当他回忆往事的时候，他不会因为虚度年华而悔恨；也不会因为碌碌无为而羞愧，当他临死的时候，他能够说：我的整个生命和全部精力，都献给了世界上最壮丽的事业——为解放全人类而斗争。——保尔·柯察金
*** 幸福
**** 刘慈欣《球状闪电》
***** 其实，儿子，过一个美妙的人生并不难，听爸爸教你：你选一个公认的世界难题，最好是只用一张纸和一只铅笔的数学难题，比如歌德巴赫猜想或费尔马大定理什么的，或连纸笔都不要的纯自然哲学难题，比如宇宙的本源之类，投入全部身心钻研，只问耕耘不问收获，不知不觉的专注中，一辈子也就过去了。人们常说的寄托，也就是这么回事。或是相反，把挣钱作为惟一的目标，所有的时间都想着怎么挣，也不问挣来干什么用，到死的时候像葛朗台一样抱者一堆金币说：啊，真暖和啊……所以，美妙人生的关键在于你能迷上什么东西。
***** 理想主义者和玩世不恭的人都觉得对方很可怜，可他们实际都很幸运。 
一种事物的美可以同它的实际功能完全分离，比如邮票，在集邮者眼中它的实际功能是无关紧要的
*** 虚无
**** 宁可追求虚无，也不能无所追求。——尼采
*** 走自己的路，让走不了的人说去吧。
*** 压力和活着（接受可能低效的规则并希望稳定持续地负担）：虚无是绝大多数人害怕的，他们宁可靠压力让自己觉得活着，一个没有压力的世界令他们难以想象，然而很多压力源和压力系统本身是脆弱的，不足以稳定地提供足够的压力。不过这样一种压力源和压力系统的停摆或崩溃本身也能提供另一种压力。
解放了的普罗米修斯：让世界感受痛楚！
人生是一场体验：我觉得的人生是一场体验 好像一趟列车 一个人上车 一个人下车 身边的人来来去去有的是擦肩而过有的陪你坐三十年 但最后还是一个人下车 你在车上可以做任何事只要你做的事不会导致你被终结 你也可以看或不看窗外的风景 最大的意义是存在 每个人都在排队等死 人人都在玩明白自己在等死 明白之后 一生的任务是怎么在排队途中不太无聊——李榛
别让“太晚了”真的成为“太晚了”
每个人生来都是君王，但大多数人在流亡中死去。——王尔德
进步或自由全面发展：不是一蹴而就的，更像是蝉蜕

荒诞：人与其生活的离异，演员与其背景的离异，正是荒谬感。——加缪
荒诞正是清醒的理性对其局限的确认。——加缪
荒诞就是死囚的鞋带。——加缪
我永远是自己的陌路人。——加缪

物质、知识、理性的枷锁：迷信的人执着于知识和物质甚至“理性”，恐惧焦虑也从中而来
*** 时间：时间是作用于器官的感觉。
死者不在乎时间。
*** 生命长度
**** 吾魂兮无求乎永生，竭尽兮人事之所能。——品达
**** 重要的不是永恒的生命，而是永恒的活力。——尼采
**** 人的生命并不能以时间长短来衡量，心中充满爱时，刹那即永恒。——尼采
*** 意识：观察者就是意象制造者。——克里希那穆提
“我”是意识最熟悉的意象，这个人形影不离。
*** 智慧：认识自己就是智慧的开始。——克氏
*** 评价：评价本身不一定影响事实，这是尊重事实者的最大的公益
*** 心态
**** 一个健全的心态比百种智慧更有力量。——狄更斯
**** 心态若改变，态度跟着改变；态度改变，习惯跟着改变；习惯改变，性格跟着改变；性格改变，人生就跟着改变。——马斯洛
**** 意志力：意志力不是用来消耗的，如果看到远处很快要有红灯，我会松开油门甚至踩点刹车，而不是冲过去停下来等[呲牙]
意志力 是个非常珍贵的消耗品 不应当在饮食这么日常的事情上浪费——李榛
绝大多数人看不惯的事多着呢，看不惯≈做不到≈不必做
不浪费有益的廉价快乐：地球上可能有超过十亿比你穷的人比你更快乐
是什么样的身份，就过什么样的生活。——逆风笑
**** 面对：有能力，才能理解，才敢面对
**** 抉择：毫不狂妄地接受，毫不踌躇地放弃。——《沉思录》
**** 真诚
***** 真诚的人，不会恨人。——拿破仑
***** 真诚也可以用渴求与误解像曼妥思投入可乐一样浇灌——kht
**** 只管走过去，不必逗留着采了花朵来保存，因为一路上花朵自会继续开放的。 ——泰戈尔《飞鸟集》第102首
***** Do not linger to gather flowers to keep them, but walk on, for flowers will keep themselves blooming all your way.
*** 好学近乎知，力行近乎仁，知耻近乎勇。——《中庸》
*** 理想主义：理想主义者是不可救药的：如果他被扔出了他的天堂，他会再制造出一个理想的地狱。——尼采
*** 对着镜子微笑的原因：向对面那个人分享愉悦
*** 懒：懒人鞋带都不系，或者没有鞋带
*** 对现象的解释：世界上有非常多的现象，但人眼能识别的只是其中一小部分（比如看不到紫外红外，每个人在某种程度上都是睁眼瞎），能解释的又是能识别的一小部分，“横看成岭侧成峰，远近高低各不同。不识庐山真面目，只缘身在此山中。”人们对同一种他们自以为客观地看完整分析透彻的现象的解释是多种多样的，爱吃辣的自然觉得那只是微辣，餐饮业也会因为大众的口味而改变标准，不爱吃辣的人则始终觉得辣和越来越辣——扯远了，世界和自己怎么样，取决于自己怎么解释感觉到的现象[呲牙]
*** 时间
*** 记忆和现在：人类的确拥有过去和未来，但他们能感受的只有现在，随后现在不断变成记忆像一摞摞文件一样堆在那里
物来顺应，未来不迎，当时不杂，既过不恋。——曾国藩
接纳自己的过去：不要害怕过去。如果有人告诉你过去是不可回复的，你不要相信他的话。过去、现在和将来在上帝眼里都只是一瞬间，在他眼里，我们都应努力去生活。——王尔德
不浪费时间：世界过分精彩，人生充满可能，我没有足够的时间浪费在相对没什么意思的事情上
*** 担心未来
**** [[http://music.163.com/song?id=33314399&userid=77770261][Wear Sunscreen (Mau Kilauea's Tropical Remix)]]
:PROPERTIES:
:id: 622c5db0-b735-411e-8bcc-75bbc8e926c5
:END:
***** #+BEGIN_QUOTE
Don't worry about the future, or worry
别担心未来，别担心
But know that worrying is as effective as trying to solve an algebra equation by chewing bubble gum
担心就像企图用嚼泡泡糖来解代数方程式一样无用
The real troubles in your life are apt to be things that never crossed your worried mind
真正的麻烦往往是你从未担心过的东西
The kind that blindsides you at 4 p.m. on some idle Tuesday
就像无聊的周二下午四点突然从你脑子里冒出来的东西
#+END_QUOTE
*** 学习
**** 学习嘛，不寒碜
:PROPERTIES:
:id: 635fb196-d0e9-49b3-9991-509e8b3420cb
:END:
**** 没有计划和计算的生活注定一败涂地。——梭罗
**** 好处：阅读使人充实，会谈使人敏捷，写作使人精确。——培根
**** 灵修使人轻松。
**** 合爱使人陶醉。
**** 造化弄人，人弄造化。——易楚
目标：这个看我要做什么事有什么目的，然后我才把可能的书搜罗一下隔段时间看，随随便便看了就是浪费[调皮]、没有目的就很难看到与目的有关的有价值的东西
渠道：圣人无常师。——韩愈
与有肝胆人共事，从无字句处读书。——周恩来
**** “知多少”
:PROPERTIES:
:id: 621ccf59-fb89-4dd6-b84c-a75effce27ca
:END:
***** ((626b7c63-80aa-4397-a100-5affdc68c3ab))
***** :PROPERTIES:
:id: 64340de4-785b-450f-94a8-a0ca5cb80ad6
:END:
>你知道的比你认为知道的多，但比你想知道的少。——王尔德
****** >我们知道的事情其实比我们认为的要多，比我们能说清楚的要更多。——塔勒布
**** 储备这个词也许意味着一种危机，持而盈之，不如其已。学会坦然面对未知，也是学习进阶的一道坎。
有限的时间不允许我像bfhsyz等大那样学习理论知识，我关心更广阔领域的实践。
知识的互通有无：如果人类达到无聊到无法无聊的状态，他就不得不开始聊了，查拉图斯特拉下山，是为了把他金杯中的水倒空
知识和技能：知识就是力量，但更重要的是运用知识的技能。——培根
所谓方法：不要拘泥于方法，它们是用来达到目的的
如果我当真偷了什么的话，希望我能不输普罗米修斯
真理：追求真理，是向它求爱求婚；认识真理，是与它相亲相依；相信真理，是用它尽兴尽欢，所以真理才是人性的至福至善。——培根
测试就是未来，而未来因你而启。——游戏传送门2第一章

提问：提问并不是要找到答案，而是去探索。——克氏
*** 艺术
论艺术--------托尔斯泰https://site.douban.com/178720/widget/notes/10281628/note/342808169/
“三权分立”：道德圈定善恶，理性权衡利害，艺术品鉴美丑
艺术共鸣（知心的作者朋友）：感受者和艺术家那样融洽地结合在一起，以致感受者觉得那个艺术作品不是其他什么人所创造的，而是觉得这个作品所表达的一切正是他很早就已经想表达的。——托尔斯泰
艺术与错乱：艺术通常需要错乱（而这种“错乱”是需要常人很少达到的高度亢奋的），所以想活得现实的人要避免过久沉溺其中
有想发笑、看不懂、学习故弄玄虚的，可以参考我这个疯言疯语本，太少了
什么都看不到时就说“禅”
现代建筑：“现代建筑”可能会给外行一种感觉，仿佛只要转一下脑袋，把房子倒过来就能成为一件新的艺术品似的，虽说只转一半可能更惊险刺激，参观者看到原本一道狭长的走廊变成了深沟，是想跳过去来到电视墙上更加低头看电视或是把电视当餐桌，还是干脆从走廊边跳下去呢？对于这种想法，也许放个厚垫子会比较安全。
把世界（重力）反过来，灯罩不就能当酒杯用了么？
*** 科学与艺术
科学帮助我们探索世界，艺术帮助我们探索自己。
只有艺术没有科学，就像被蒙住了双眼。
只有科学没有艺术，就像被蒙住了心灵。
——知乎“带月荷锄归”
* 社交
:PROPERTIES:
:heading: true
:END:
** 当世界点我名时，我很难不吭声，我早就上当了，并乐在其中
朋友：朋友不就是纵使认为你误入歧途但仍为你守侯的人么？
朋友就是在别人不看好ta，甚至ta自己都不看好自己时，依然相信ta能变好的人。
** 神遁：所谓神谕，即把凡人的智慧和力量归功于神，这样做能够表现谦虚、促进合作、牵制嫉妒，但并不能解除部分人不满的蓄积
** 骚话
*** 要是我钻进去了（指被窝），我们还能回到现在这样较低水平的关系中吗？
*** 我这人喜欢通过聊天了解世界
*** 我真的是讲究吃东西的整体体验，只有很现实的场景我才会去餐馆吃，要么是陪客户，要么是出差——你不是现实，是梦
*** 主要是想见你，最是你让我感到了被倾听的美妙感觉，其次顺带带网友也蹭蹭你的影响
** 喜欢与不喜欢：我听从本能的号令，别人不喜欢我与我喜欢别人并不矛盾

为何聊天：倒不如说entp喜欢不确定性甚于社交
聊天创造了一个不同于独处的情境，使得某些意图通过聊天来学习的人可以为刚刚或重复发现的问题准备答案或素材
怎么说话：所谓“所谓情商高，就是会说话”，至少我从功利主义的角度出发是赞同的，见人说人话，见鬼说鬼话。
关于社交难的骚话：打开话匣子是很简单的，自言自语就可以了，也是很难的，不一定有人能听懂，或者以为没人听懂，其实事实是懂的都懂，但是又不敢说出来，因为网络并非法外之地，搞革命的事是不能随随便便在没什么群众基础的地方说的[呲牙]
其他骚话：人类熬夜后，共产主义就如土豆炖牛肉一般近在咫尺（注：我自己又看时联想到996）
骚话风格：也可以把看似复杂的说得让人发笑、看不懂、觉得故弄玄虚
群聊骚话多的原因：为了避免群里的女同胞误解，我还是要解释一下：这可不是pua，这只是作为良好习惯的走向世界的日常爆炸性发言[呲牙]
满屏荒唐言，一把辛酸泪。都云虎鲸吃，谁解其中味？
撤回：没必要问这种问题，人们试图撤回的大多是自己的青春，虽然永远无法撤回
几个字一行的原因：可能是想随时有意无意迸出或连成一首诗
为何聊不下去：你在xx方面懂得多，能聊的不多
避免被举报：不能因为到了一个新群看到几个认识的人就罔顾还有很多人不认识的事实开始说骚话

”顾问“心态：一点都不神奇，这样的笨习惯我也想改，哪怕不能解决问题。我们这些“顾问”老唯“物”不关“心”了+
如何劝说：多问情况，少讲道理
** 群聊效率
*** 群聊的问题增生：等一下
** 自动就是不是自己动
** 夸奖
*** 喜欢好看：这么说没错，对于唯美主义者而言，美就是最大的正义，王尔德说，“只有肤浅的人才不以貌取人。”
** 掉书袋：要是说话全靠掉书袋那才叫强呢，我还差得远。
提前写好：为了更精彩的聊天而写草稿有文德吗？有，这很好。
** 争斗：来逗我呀！
（无论看了哪些方面那些立场的专家学者的哪些文章或自觉有什么高明的想法，）不要让诸如“我是对的！”的信念绊倒自己
** 掉书袋：他们几百几千年说的话，我帮他们带到202x年和我们的话坐在一起，这不是帮他们实现永生么？
** 谈论自己
*** 完全不谈自己是一种甚为高贵的虚伪。——尼采
*** 常常谈论自己的人，往往只是为了隐藏自己。——尼采
*** :PROPERTIES:
:id: 63872aeb-5e95-4db9-8818-93de4cb4ce1f
:END:
>坦率地说出自己的心里话不仅是一种道德上的责任，而且还是一种令人快慰的事。——王尔德
** 语言
*** 语言是工具，抛开其内容的真伪和形式的简繁不谈，只要我觉得有必要我就使用语言。
*** 语言是麻烦的帽子，我尽量不戴帽子，人就一个头，不够戴。
*** 怎么说话的：见人说人话，见鬼说鬼话，这是语言能力强的人才可能做到的事。
*** 如果你既不能理解比你聪明的人的话，又不能理解比你笨的人的话，那么看来你只可能理解你自己
*** 我在随意描绘一大堆人
*** 缩写：缩写并不方便记忆，但省事。
*** 语言作为自己的陷阱：语言就是有这样的魔力，即便刀子钝了，舞在手中仍旧呼呼生风。
*** 语言用不好就是行走的地面都不稳固
*** 名不正言不顺事不成，一个词的多个概念（无论词典上是否有你的释义）、多个词的一个概念打架，也可能是你纠缠不休的一个原因
*** 这样好比不断地从一个梦逃到另一个梦
** 表情
避免滥用聊天表情：有时不加表情是为了避免表情的反噬[发怒]
不加表情，节省了写作时间，扔掉了原本用不着的拐杖，深刻了不用表情时的文笔[奸笑]
狗头置换：从一个现象出发，我出于“避免想表达的意思和珍惜的人际关系被并非本真的表情扭曲”的原因戒掉狗头好一阵子了（可以经常用表情，但要让它们在可接受的范围内与真实感情步调一致），但是外面处处可见，虽然它通常首先是“无意冒犯”的意思，但很多人会把它和（“毕恭毕敬的”）“单身狗”等联系起来，这些是打在自己身上的标签，标签总是容易先去掉的，面具则不然，戴久了就摘不下来了——也许标签贴多了也就成了面具，而且像是某种下葬时才需要的面具。
** 个人历史研究
兜圈子：还有一种担心：自己费力思考的结果是自己早就想到过的，乃至否定过的[调皮]在很多次从记录中发现“兜圈子”的现象后，记录者造了一个“时间军衔制”，过去的我是一个个真实存在、互有短长的断面或切片，现在的我需要努力让他们成为好参谋好战士而不是过时的散兵游勇……[呲牙]此外还有一种担心，一个大家能理解的概念，也许有人走别的道路，已经领先很久了，不过我们还是会为自己适应的走路方式和在自己的路上沿途发现的美而陶醉[奸笑]——易楚朋友圈
面对自己的经历
自省：拒绝或放弃自己的经历就是要阻止自己的发展，否认自己的经历就是自己对自己撒弥天大谎，这无异于否定灵魂。——王尔德
吾日月年旬世三省吾身
** 写作
*** 作品不是我。
*** 更新之痛：你要是有几十篇文章可以改的话你也会烦的
不更新的理由：还是继续向前走吧，希望读者都聪明到以自己学习、自身体验或最新标准为准，不要被我可怜的老文章绊到
*** 普通人的爱好：平庸的写作有如半盲人的雕塑，如此也好。
** 观点
*** 秩序：为什么重点提秩序？因为我们大多生活在一个有秩序，至少我们相信相当有秩序的世界，要想帮作者本人和读者保有或找回自信，最省力的事显然是先给一套还不错的秩序让这个世界更有秩序感，一目了然的秩序感、征服感、掌控感。
*** 规则：在打破规则之前必须清楚规则是什么。——robin
*** 变态：变态是常态。
易就是变，变化就是容易。
*** 死亡：没人愿意死去，即便是那些想上天堂的人也不想通过死到达那里。——乔布斯
死亡就是倒放的起床，有些人一跃而起。
死亡的声势比死亡本身更为恐怖。——塞内加
成人惧怕死亡恰如儿童怕进黑暗；儿童天生的恐惧随着故事同步增长，成人情况亦然。——培根
有些人二十岁就死了，等到八十岁才被埋葬。——罗曼罗兰
*** 没怎么好的旧伤：如果缺失更基础的东西，以后对别的东西也会不上心，无论它们本身有多好，欠的债总是要补的
*** 知识的层级：关键看你在哪一层？
只看一层是容易的，从表层看到里层难一点，把表层里层穿起来则难上加难（注：当时字打得快，穿更应为串，当时看到了不在意）
我不以班门弄斧为耻，它是谁家的门重要吗？
** 山：山无处不在。——刘慈欣《山》
仙看上去像是倚山而居，所以豹豹是仙
人生何处不青山，人人皆能成仙，关键就看他是否能自然地走向山，无论有多少山，山有多高
登山的过程中，人山合一，如果山上植被够茂盛的话，我们甚至不知道人在哪里，但是山泉会告诉我们这座山是很了不起的
前面的登山者，也是后来者要登的山
你不是山？难道你是人吗？
** 各种解脱道
*** 克里希那穆提说不需要任何社会，因为社会定义了自由，而人的自由不甘被“定”义——我可以想到古代开悟者也不需要地铁手机座椅屏幕键鼠来修行，然而，从克氏思想的反响来看（相对而言，是知易行难），似乎各种或长或短的方法都有其不足，克氏的方法简单，但至少同等需要慧根。马克思主义认为人的欲望是无限的，这首先在物质层面与灵修者们的观念有碰撞，为了修道，我需要吃到怎样的食物，睡到怎样的卧榻呢？这些基本需求，如果只是每天从冰箱里拿出一块好肉津津有味地做了吃掉，也还不算什么大问题，但那之后，人要是看这想那，他真的总能满足？光速在哪？死亡在哪？（顺序不影响阅读）而在自然科学方面，一个慧根即聪明且有发展智慧的潜力的物质的头脑，如果要多很多，那么就需要研究基因等方面的科学......如果要一个慧根是为了搭上克氏的车（至少作为一个目的），那么我们先有土豆炖牛肉还是后有土豆炖牛肉似乎都差不多，是这样吗......工业的聒噪和内心的宁静，不能和谐吗？“良质”！我又想到了那本书，大概书和演讲都是不冲突的，我并不是被一个什么人告知了“具体该怎么做”。“明白四达，能无知乎？”我可能不需要这些玩意儿，暂时。
** 经济
*** 货币
**** 银行：银行从业人员，因为银行本身业务特点，也许还是就这么多亲属关系对社会和家族比较好
*** 市场
**** 楼市
***** 楼市不稳跳楼的人就多得多了，房子不能抽（烟草的一氧化碳，“气体”）、不能喝（白酒，液体）、不能噶（韭菜，脆弱与强韧兼具但较少反脆弱的固体），最关键的是不能像前三者及其附属物一样“不知所踪”，是一般人的血肉之躯难以啃动撼动的强韧固体，是暂存其余的仓库，是堡垒，更是囚牢
**** 股市
***** A股：购物清单都没有，全凭感觉购物，怎么会有长期投资呢？但也因为超市里只有这些货，而且来超市看鸡蛋大米的中老年人还不少
***** [[https://zh.moegirl.org.cn/%E4%B8%8D%E8%A6%81%E6%80%95%EF%BC%8C%E6%98%AF%E6%8A%80%E6%9C%AF%E6%80%A7%E8%B0%83%E6%95%B4][不要怕，是技术性调整]]
****** [[https://www.bilibili.com/video/BV1Aa4y1a72c][不要怕 技术性调整]]
** 政治
*** 文明：对文明的真正检验，不在人口多寡，不在城市规模，不在庄稼产量，而在于这个国家造就了怎样的人。——爱默生，游戏unciv
*** 英雄功业：英雄人物是以整个大地作为自己的陵墓的，他们的英名不仅凿刻在有形的石碑上，也在千万世人的心中留下了无形的印记。——伯里克利，游戏unciv
*** 得有人先生活
*** 孟子见梁惠王。王曰：“叟！不远千里而来，亦将有以利吾国乎？”——孟子
爱民治国，能无为乎？明白四达，能无知乎？
圣人无常心（或“常无心”），以百姓心为心
在一个聪明人身上所产生的印象就是，万物都是无辜的。——梭罗
** 善良公民的政治思想进步：从试图承担无限责任到有限责任
要多想，反反复复地想
一心寻愧的话就总是能找到的
就一个方向？就这？
在发现所谓“最好的方法”前，先用“能用得上的比较好的方法”。
** 商业：商业也是罪大的工艺
*** 我做出来配方，你们自己做不就行了，毕竟商业就是最大的公益
** 内卷：既来之，则安之，万类霜天竞自由
** 历史的特性研究和感恩节梦话记录：感恩上帝使我们在新大陆安居乐业
不过，如果允许对历史进行分割单独观察，并且那是史实的话，好像感恩节也的确可以有
后面发生的事，不影响当初的善事善心，你看那多少个民族已经在历史长河中渐远了，但他们的故事不还是能勾起现代人内心的崇高感情么？
我不会说，历史是有立场的
有潜力总是好的，是不是公知，得看你在人类舞台上起到什么作用
如果想要保持“正确”，那就安安心心待在温暖的屋子里，看外面上演的各种戏码就够可乐了
公知和我们也许不在一屋，但是也许是觉得无聊，或是没火鸡吃，也许是看到外面变得热闹了，他们就跑出门加入了，然后我们看到的戏就更精彩了，我们可以放掉一只白火鸡，但是肚子饿时，已经出炉的其他更多火鸡还是要吃的，粗糙的肉质，配上常读常新的故事，才勉强能让一个平凡的日子有点不平凡地过去
** 国家的难处：国家的资源正如个人的资源，都是有限的
** 行业人的区别：公务员、国企员工和资产者的性格在整体上无疑是有差异的
** 灵魂枯萎的先富：什么是“先富带动后富”？“富”是什么？只是兜里的钱多吗？如果灵魂枯萎，花再多的钱也很难拯救。
** 团结：把人类拧成一股绳
资本家与平民的直接对话：资本主义的发展需要个人之间的契约，人再多也能给你弄个法人出来，个人主义、“民主自由”、“精致的利己主义者”这些都与资本主义有关，你打开多数美国人的心，看不到什么“同甘共苦”“同舟共济”“集体高于个人”存在的痕迹，除了自己和家人，多数别人是可以了无牵挂的，这就是“自由”，不像中国人还有部分欧洲人别说当下了甚至会为古人古事哀叹，美国人看各种fake news时，不是一群西方记者编导什么的给美国和世界整活，要清楚，那其实是个人之间的关系，大资本家通过代表和直接传达他们意志的媒体用fake news与美国和受美国不同程度控制的国家的平民“对话”，“团结”被尽可能地规避和破坏，大资本家需要尽可能多的一盘散沙般的平民。人类不经历失败是不会改变的，我们有的是血的教训，所以我们更珍视现在的生活。
资本家对资本的浪费：他们就这样随随便便地把工人生产的资本浪费掉了
人很难吃得干净
斗争：门阀们有一套秩序稳定的体系，我把它们打散了
人们为了利益而集团，然而首先是基于自身利益选取适合的思想，再从思想出发选择与更一般的利益结盟或交战，在实际操作的意义上，对利益的斗争自然包括思想之间的斗争
你们不相信阶级同志，倒蛮相信资本家和所谓工资
什么可以被说成“人类”：包括我自己在内，我们常听到某某人说“人类”怎么怎么样，但是有时我们也会发现自己对于“人类”没有一个固定的百试不爽的用于界定人或非人的概念，从不同的角度，我们可能会把别人视为“人类”的视为“非人类”，比如以下很常见的表达方式∶“你还是人吗？”“你不是一个人”。反过来也可以，对于亲昵的宠物人们会对别人介绍时用上“儿子”“主子”之类的称呼，对于某些鸟类鲸类等有灵性的动物人们可能会把它们拟人化比如说做成头像。
改变人类社会的策略：你不需要一开始就找那些难以为继或罪大恶极的人去改变，毕竟你不是神，改变的顺序可以是这样：与你相似度为0.8的朋友——0.64的朋友的朋友——0.512的朋友的朋友的朋友——0.4096的朋友的朋友的朋友的朋友——0.32768的朋友的朋友的朋友的朋友的朋友——0.262144的朋友的朋友的朋友的朋友的朋友的朋友，根据六度分割理论，搞定。改善自己的生活，用不着让全世界先改变
我的延伸：我首先想改变我自己，把他改变成一切
** 社会化抚养
*** “老吾老以及人之老，幼吾幼以及人之幼”
*** 很多人都在说自己的原生家庭怎么样怎么样，我相信其中大部分都不是空穴来风，并且还可以迎合一句，人可不能给自己的投胎买保险。不过事已至此，你要抱怨多久呢？让我们现在就把社会化抚养办起来吧！
*** 血亲纽带不一定好，但通常还是比较强（至少是约束），而且是生来的
** 阶段
*** 学生
**** 跨时代的存在主义危机：晚几届的学生大多总能够（可能还有必须）在更早的年龄接触到更新更丰富的知识和体验，“我”永远被生早了（也可能生晚了），这是可能被想到的，当然你无从选择，有时是好是坏也难说，95后甚至00后才算充分普遍地被能随时随地上网的智能手机日夜监护（更早的多数人是高考完才拿到手机才能时刻接入互联网的），之前的人们就不用为了这样一个小东西劳神费心。这不免让某些人想到，我是不是在这方面该模仿一下长辈？我是不是该体验选择重构一下我的生活？
**** 手机电脑：我能看到他们那些“看手机的眼睛”、你们好！手机的附属品！
知行分离的网络知识或信息：屏上得来终觉浅，绝知万事要躬行
你有亿件事可做，你能做好一件事吗？
*** 社会
*** 被时代拖着走也总比时代拖不动好得多
xx后：更多是必然经历的时代特点、社会背景、共同事件，而非个体人格
时间之河：我们这些多数，也很快要成为少数
最好和更好：最好是谁的呢？
** “体面框框”
*** 把食物从框框里取出来吃掉（人就不会饿了；精致一餐的框框、相机的框框、习惯的框框、每事问的框框）
*** 框框（无处不在）（，让生活更糟糕）
*** 每个时代有不同的特点，但很多过去时代的缺点也会继承
*** 面子害人
**** 这样的体面难道不是奴隶的体面吗？
**** 批小将的可能成因（对别人造成自己自尊受损的不接受不接受且要倒打一耙的）：人受多了批评，便要批评
** “现代化”
*** 无论“现代化”化到什么程度，人们怎么一边在怀念过去美好时光的同时对孩子不用“更高级的玩具”、“重复造轮子”的行为感到不解和焦虑，一代又一代的家长们总还是要先让婴儿在ixpe、pvc垫或更花钱或更省钱的路面爬行，也不得不默许幼儿以各种难以预料的方式在家里搞出“麻烦”的天性。
*** 人们为了一个并不有利于自己的“唯一”标准牺牲自己和他人的幸福，这就是“现代化”吗？我们的炬火，我们的圣火，我们的更好的道路呢？牺牲者退下来，忍气吞声地做着并无多少创造的工作
*** 现代文明生活是一种温柔的凌迟
*** 和平淘汰：要说强力意志吗？
** 城市
*** 对长居一般城市的态度：“鮟鱇~你喜欢这座城市吗？我非常非常喜欢。但是所有的一切（包括自己保管的遗传信息）都不可能永远延续，不管是快乐，还是欣喜，全都......全都不可能永远延续。即使是这样，你也会喜欢这里吗？”
*** 外地的大城市（海鲜、筏）：嗟乎！一人之心，千万人之心也。秦爱纷奢，人亦念其家。奈何取之尽锱铢，用之如泥沙——阿房宫赋
:PROPERTIES:
:id: 62bcf8a5-0206-4380-8919-2c626cc9fc2b
:END:
*** 我们内心的恶魔，把这座城市变成了地狱。——王尔德
*** 有些人说房地产是蓄水池，可这是谁的水池呢？它放不放水呢？此外，很多感觉渴急了的人往水中笼里跳，水位越来越高了
*** 你们把过半工资交给了房东和银行，还好意思说最爱那个ta？
*** 房产税，从哪出？买房的人，还有更重要的租房的人、
*** 我们的房屋是如此笨重，我们往往不是住在里面，而是被囚在里面。——梭罗
** 非主流生活方式：他们在这里或还没到这里的那里偶尔感到的一点莫名的恐慌，与其说是“过度自由”这种凭空生造的原因带来的，倒不如说其实因为在他们四周还存在一个老大的充斥着恶意的社会背景，认同压力由此而来，是继续勇敢地做自由的子民呢，还是走回那群戴着面具的奴隶？这种恐慌带来的有意无意的思考需要他们做出很大程度上与“文明社会”决裂或重返“文明社会”的有生以来最艰难的决定。“举世非之而不加沮”，行吗？“文王既没，文不在兹乎？”
** 住房
*** 极简装修：我可能会极简装修，乳胶漆什么的刷刷完事，先给房子一个色调，然后水电简单弄弄，最后整理好的背包或行李箱打开就能过夜了，出现缺少或可逆的问题再继续研究，让它一直是我想要或至少能接受的样子[奸笑]、如果让孩子也能一起装修，并且能一直装修，岂不美哉[奸笑]、已经完成的作品，没了给所有孩子变动的空间[呲牙]
** 生育
*** “但愿我生出超人！”——尼采
*** 婚育制度：皇帝（包括女的）相对于平民算不算一个“更进步的人”？如果人人都有皇帝那样的条件呢？那就确实可以如各种人所言共产共夫妻了，前提是别人醉心劳动和已有情人之余还看得上你
*** 大家的基因：没有谁拥有他自己的基因；他只是基因的监护人而已。——海因莱因《时间足够你爱》中的拉撒路说的话
*** 关心人类的爱情，性爱只是一种有用的动力，更多为的是人类繁衍的优化或避免进一步劣化，为了更多更好的后代，而不是更少的残废
*** 为延续者祝福：ta已经选择了遗传配方，我们现在看到这配方效果还是不错的
*** 一丢俱丢：人类文明本身就是对基因代表的自然秩序的反抗，当花不愿为了孢子而战时，基因传承的效率自然会受到很大程度上的干扰。但问题是附带内容的损失
:PROPERTIES:
:id: 626bcab7-6a9e-4ab8-9fe0-ccc93671d7f8
:END:
进化心理学与男女生理差异：大家都或多或少了解过进化心理学，生殖策略取决于生育成本，生育成本又取决于生理结构，男人没有子宫生不了孩子，不需要为了基因竞争保持更长的头发等第二性征，不需要为了胎儿吃好喝好负重前行，也不会正常情况下每个月掉血，也没有每个月就那几天能加入人类演化的限制，所以一般地会比女人浪很多，这在演化上大致是一种合理的妥协，毕竟人不知该怎么下蛋，胎儿也不能分成两半，假定能百合生娃把男人变成更复杂精致美丽的女人可能也会因为消耗营养更多而不利于更高效的物种扩张，如果女人能有机会把孩子给男人生的话男人也就成了女人，额……但他们还是有烦恼的，正由于上述理论和其他方面的各种原因，他们
** 教育
*** 生育年龄对父母的影响：事实是，生育适龄更多取决于女方年龄，就目前的条件而言，女性超过35岁一般说来就不太适合再直接生育了（冻卵是一种应对时间流逝的方法，一种“期权”），除非对“辈分”这种东西能有所创新（比如“半辈”）以减少部分不协调，如果前面有生那就还有哥哥姐姐能客串起到一个部分类似父母的提携的作用、辈分没有“半辈”么？然而小家庭通常情况下填不进来一个“半辈”（比如早生的哥哥姐姐或喜欢别人家孩子的亲戚），给不了孩子更年轻或者说更丰富的家长体验……唉，人类[抠鼻]
*** “代父/母”：如果生育年龄较高
*** 自律管理的新职业——家长：家长管教没落下，自我感动、人不会因为生了孩子而突然变成合格的父母
*** 当他们从小就不断接受过于苛刻和违背自然的“被教育”条件后，难道还有理由指责他们过度“路径依赖”吗？
*** “看！这是我生育和培养的孩子，ta多了不起！”——家长
*** 光说不做假把式
*** 归零的作业：一份份作业是不连贯的，孩子没法在不停重开的过程中获得自我成长的力量