* 不仅要分类和猜测，也要有报价，像是文明系列国家贸易，要素综合价格等式
* 以下页面链接可根据自身需要的优先顺序阅读（以适当的方式，适当的顺序，做适当的事情）
* 引用
** 需求就是现实与期望之间的距离
** 饥而欲食，寒而欲暖，劳而欲息，好利而恶害，是人之所生而有也。——《荀子·非相》
** 没有计划和计算的生活注定一败涂地。——梭罗
* 观察（什么在发生？）、需求（我这个身体想要什么？）、选择（做什么；时间统计，剔除无关活动）、效率（什么、多少、如何，我的状态怎样；时间统计，优化活动流程，包括何时活动者状态最佳）
:PROPERTIES:
:created-at: 1626583197412
:updated-at: 1626583212197
:END:
* 十欲：暖食息色香，笑（搞笑）思（思考、笔记、写作）说（演示）动（电子游戏、健身）赞（倾听）
* 等级（不一定线性、连续）
** 精力
*** 体能
**** 卧床不起、瘫坐一坨、出门散步、连上五楼（在能够一分钟连上五楼前，要优先努力健身）、引体向上（适当补个有益上身健康的）、单腿深蹲、单手俯卧撑、力能扛鼎（硬举；对抗重力的体能是最综合的体能：[[https://www.zhihu.com/question/373511126/answer/1608008791][举重运动员有多牛？ - 运动分子的回答 - 知乎]]；身动如山移，出手如压顶。“用力气掌控他人。用力量掌控自我。” [[https://cultist.huijiwiki.com/wiki/%E6%8A%80%E8%83%BD%EF%BC%9A%E6%97%A0%E6%95%8C%E4%BD%93%E9%AD%84][技能：无敌体魄]]）
*** 精神
**** 昏昏欲睡、恍恍惚惚、闷闷不乐、炯炯有神、精神饱满
**** 安全感：惶恐不安、惴惴不安
**** 人生意义：
** 财务
*** 支出
**** 饮食、交通、居住、无业无忧
** 时间
*** 空闲
**** 夙夜不懈、忙里偷闲、
*** 效率
**** 无事生非、拖泥带水、抓耳挠腮、步步为营、势如破竹
** 社交
:PROPERTIES:
:id: 60b05d82-24da-406f-ad61-88a217eeabce
:END:
*** 需求
**** 我、他、我和他、我们、我们和我们
*** 质量
**** 忍气吞声、怒火中烧、阴阳怪气、无话可说、有口难开、试探、无话不谈
* 引用
** 所谓诚其意者，毋自欺也。——《大学》
:PROPERTIES:
:id: 622368cf-e038-41ec-a54d-07b4189e4038
:END:
* 人的需求如下（相比马斯洛的需求层次理论，以下这个是相对实用、可以互换的；能满足人的需求的不一定非得是生物，甚至不要几个钱，例如清新或香甜的空气、用手机电脑听的音乐看的视频玩的游戏等，虚拟的钱、劳务等也是有用的）
* 财务
:PROPERTIES:
:heading: true
:END:
** 钱/资金比较通用、方便；消费，销售，投资，资助
** 消费
*** 如房租、食材支出。一方为另一方消费，部分是信号，即通过实际行动判断对方实际可能有多少钱、愿意花多少钱等，也有的就是把人当会自己跑的卡刷——遇到想白嫖的当然能教育就教育一顿啊
** 销售
:PROPERTIES:
:id: 670d4142-5892-412c-8917-da02db9fd0cb
:END:
*** 参与促成消费、投资、资助等，有或多或少的提成或人脉收获等。有身份通常较明显的，如谈判（“砍价师”）、带货、卖理财产品（包括代销的）、开信用卡/会员卡，也有做托的，如房托、酒托、零食托、气氛组、刷单，还有相对中性的软文软广告
** 投资
*** 简单地说是偏向钱生钱，如买茅台、买房、买基金、健身、护肤、化妆、抗衰老、教育
** 资助
*** 也许可以算“投资人”，为了通过受助者实现独自难以（专业素养没有或不够，或是必须出钱才能做到，如通过慈善避税）或不方便（不在那地方那行业）或不愿亲自（如可能被反杀、报复的谋杀）实现的目的。
*** 通过私人支付的较高端形式有资助哲学家、艺术家、科学家、政客、说客、刺客等本身没有可靠收入来源的精英（虽然有些人的业务能力不比大众化的历史意义和评价），例如米开朗基罗、达·芬奇、毛遂、荆轲，还有资助底层群体且可用于避税的慈善
*** 大众化的资助方式则有捐助（针对自然灾害、医疗等）、无息低息贷款（针对待业等）、打赏（针对街头表演、网络直播、内容创作者等）等
* 劳务
:PROPERTIES:
:heading: true
:END:
** 一般劳务，至少消耗精力和时间，部分或全部可由他人代劳者。大多需要明显比付款多的时间和行动，消除的可能主要是“烦闷”（这题怎么做卡这儿别的我都不想做了好烦、这人怎么还没回消息怎么办、中午吃什么晚上吃什么、来回跑要多久多少钱、怎么要付费看怎么大会员也要付费看）
** 业务：学业、职业等，同业往往互抄作业、共同进步，可能包括“与孩子一起攻克难关”
** 家务：交通、饮食等，即送人、送物、做饭等，要么它比直接用钱买的便宜（但实际上常常并非如此，如果将家务的货币价值与工作的工资等同，那么洗碗机、烘衣机、洗地机等一般两年左右即可回本），要么它能够提供更多安全感等
** 解闷：音乐、影视、游戏、阅读、写作、运动，陪伴、对话、抚摸（猫狗兔鸭等），旅行、逛街、购物、唱歌、跳舞，吃肉、喝酒等，无聊烦闷、逆境苦闷、遭罪郁闷、累了也闷……休闲可能不容易
* 安全感
:PROPERTIES:
:heading: true
:END:
** 有恒产者有恒心，无恒产者无恒心——任何事物（包括自己的生命）都会变化，人们的安全感主要来自现有利益（财务、劳务等）“不会或不易失去”和“变得更好”的期望——于是，人们常要参与到某种事情当中（包括似乎不会变化的“空”、“无”）感到（但不一定被广泛认可）自身与事物的联系（使其“不会或不易失去”或“变得更好”）才能有充分的安全感。
** 世上有很多因素能杀死或耗死你，而保护你的主要是随机性和所有出于各种理由希望你健康存活乃至自由全面发展的人。通过人直接间接获得的安全感的来源除了“老天爷”“仙人”“天子”等虚构人之外就是现实人的各种角色，包括权威、顾问、亲信、代理人，宠、夸、恩人，亲人、恋人，以及觉知与评价的自己。
** 办事
*** 权威
**** 给人免去跋涉求索之苦劳的希望
**** 引用
***** 一群新来的学生可怜兮兮地跟在主任身后，他们都很年轻，朝气蓬勃但阅历尚浅。每个人都拿着笔记本，只要这位大人物一开口就忙不迭地做着笔记。这可是权威可靠的信息，机会难得。
权威可靠的信息，机会难得，抄到笔记本里。这帮男生疯也似的抄写着。——《美丽新世界》
*** 顾问
**** 主要是讨论和咨询问题。前两者很大程度上是通过获取知识产生的安全感，例如作为权威的教材和媒体，作为顾问的百度知道和知乎回答
*** 亲信
**** 容许其知道秘密，即不想大部分人获取的有关自己的知识
*** 同好
**** 有相同爱好者，解闷等所需
*** 代理人
**** 包括部分仰慕者（可能包括部分“舔狗”）、保镖、助理、经纪人、资助者等，他们也许能帮主体摆平不少难事
** 宠夸恩忠
*** 宠
**** 相比于代理人，宠（部分算是一般意义上的“溺爱”；反面也许常是“冷漠”）更能被乐意且充分地给予，他人接受自己的有效（即被接受）善意也是安全感的来源，宠物、孩子抗拒抚摸、进食、奖励了可咋整？
**** 引用
***** 我只想给你给你宠爱，这到底算不算爱，我还搞还搞不明白~——《青春修炼手册》
***** 我认为所有漂亮的人都是被宠坏了，而这就是他们能够吸引他人的秘密所在。——王尔德
**** 除了出于可能并不罕见的禀赋和运气的连续被宠和/或宠的生活经历的影响外，部分男女受网络小说、动画等的影响而有迥异的对宠和被宠的偏好
*** 夸
**** “赞美”，反面有包括嘲讽、捧杀在内的辱。从实际效果看，有意无意都算，整体上，有效的夸相比宠更多建立在事实基础上，有效的正面评价符合被夸者为自己雕塑的正面形象（“此人很有眼光、通情达理”），有时一句简单但罕见的正面评价就能滋润一颗在较深度社交方面或多或少干涸的心，令人铭记在心难以忘怀。
**** 引用
***** 爱情，就是夸大一个女人与另一个女人之间的区别。——萧伯纳
*** 恩
**** 一类深厚情感载体，发现、构建和表达感恩对人非常重要，“投我以木桃，报之以琼瑶”。如养育、教诲、赏识、救命之恩。
*** 忠
**** 一般是大恩报答完之前的状态，所谓“三生三世”、“七生报国”（？）
** 亲人
*** 保证关系不太差的基因下游/上游的安全、身心舒适和人生阶段发展顺利也是安全感的来源，即慈、孝，大概也是多少“刻在DNA里的”，值得一提的是，人们通常能发现部分家庭亲人之间对安全、身心舒适和人生阶段发展顺利的认知或多或少并不一致。
** 恋人
*** 性欲
**** “刻在DNA里的XP”，人生来就有、因为被压制而显得更特别的东西
**** 欣赏：外貌、声音、气味、性格等，自我欣赏包括自恋，被欣赏包括男/女性凝视等形式（可能也带有宠等意味）
***** 我每天都要看妞，没有别的想法，只是为了我的心情愉悦。——“你大爷”
**** 身体接触：牵手、抱、摸头等
**** 性爱（大体上算是相对特殊的身体接触）：合爱（不含性高潮，甚至可不含性交）、传统性爱
*** 夫妻（经历了事实婚姻的恋人）
**** 在人际关系方面有效的婚姻在能够减少散乱、延长现有关系的保质期、提升多种多样的安全感，因为这通常是一个人、两个人、一家两家人和更多很多人不同程度参与和见证的契约，比较平等的双方有望“永结同心”，而相对受损的一方可能就此不去计较“钱包开口、功业受阻”等沉没成本，相对收益的一方则可能飞跃到心安理得同时负责支持或参与的高境界，这是比较好的可能。婚前：私下承诺、家庭/家族赞成、结婚登记、婚礼引发的名誉/支出/仪式，婚后：财务/劳务分配
** ^^自己^^
*** 此库关注的核心是人的自由全面发展
**** 天行健，君子以自强不息；
地势坤，君子以厚德载物。
*** [[https://baike.baidu.com/item/%E4%BA%BA%E4%B8%8D%E4%B8%BA%E5%B7%B1%EF%BC%8C%E5%A4%A9%E8%AF%9B%E5%9C%B0%E7%81%AD/6726788][人不为己，天诛地灭]] 。即便生来富贵，但自身能力发展得不够，一样可能遭受厄运
*** 过度劳累就是消耗自己的能力和潜在成就
*** 自身之内的安全感和恐惧等往往最恒久——“吾所以有大患者，为吾有身。及吾无身，吾有何患？”（《道德经》第十三章）人大多不同程度地惧怕疾病、衰老、死亡等，怎么办？
**** “虚其心，实其腹，弱其志，强其骨”（《道德经》第三章）
**** 维持和发展来自自己的安全感的方法常包括“强身”和“忘我”两要素，前者如体育、美容等的一般主要部分，后者如实修（最常见的方法为相对舒适的静坐）、功业、好奇心等的一般主要部分，前者在整体上更容易往“自己”身上贴挂，后者可以减轻贴挂的负担（设定和被投射的过高目标、维持美好形象和虚名等或背负或高悬的身心压力等）——但实行难度由于社会等的影响一般更高、更难持续（包括看搞笑视频）
*** 时间
**** “没有自己的时间”，意味着没有时间发展自己，自然容易引发不安
* 人生中不存在任何必须的事情，只存在不必要的期待。——卢安克
* 通常一个人并不需要“积累”到某一“社会必要水平”才能达到满意的个人幸福水平。相对明智的人选择（至少暂时）放弃部分行动，把很可能亏损的项目砍掉以最大化实际可能的幸福。例如，人类完全可以通过宠物（“提倡领养，拒绝购买”，可谓一箭多雕，省钱、交情和可能的圈子等都有了）、网红明星艺人（“老铁没毛病！”）、虚拟人物（游戏、动画、小说等。“远离帅哥美女的人”可能相对爱看）、手办（转了次元，不能动了，摸得着了，风险大了）、X玩具（“没性伴侣前先用手之外的工具更舒服地释放性欲”）等获得不太差、也算稳定的满足，所以该怎么选？
* 自我实现
:PROPERTIES:
:heading: true
:END:
** 老掉牙了，但是一直有——膨胀的前述需求、力量/体育享受、实修/高阶健康体验（心流、精神飞翔）、名誉/能够公开的夸（称号、奖状、牌匾等）、功业/群体目标的实现（培养家族晚辈、建立和保卫新中国、每个人的自由全面发展、人类解放等）、好奇心/对真理/自身/事人物的能力和局限的好奇心......相关内容大概也可统称“高级意义”，其实也可以把它们归为安全感——有默默无闻、就此涅灭的恐惧，就存在对安全感的需求）
** 优点
*** 当你设定了一个足够大的目标
*** 我选择的目标远在天边、近在眼前，远在天边是说人类、人民之类的概念一般而言很大很远，我不用太把自己的幸福绑定在某个事人物上，近在眼前则是我确实能够经常发现具体的幸福，毕竟世上事人物是很多的，例如有这样格局的写作，素材到处都是，都不用自己找就能跳出一大堆
*** 人类和人民是很难对我表达确定的不满和否定（可能会有个人，但不是集体）
*** 我不用担心自己的一点观念或行为上的一些小错会对历史进程有多大负面影响，而在长期具有了方向和动量积累的稳定性和反脆弱性
*** 此身未有神仙骨，纵遇真仙莫浪求——在需要面前，你的身体素质都可能在各种方面拒绝你，但“人类”不能
*** 高性价比的
*** 你开启这方面的视野后，集体的需求也是你的需求了，集体的要素也是你的要素了——你必不至缺乏，只是忙起来了（很多东西都没我脑子里和笔记上要搬空的东西重要，于是我成了这些大山、宫殿等的囚徒）
*** 自身生活成就的重要性可能会下降，不用太烦神了
** 可能有用的阅读：犬儒主义者、现实主义者、理想主义者三者有何区别？、马斯洛：自我实现者的十九种特征
* 以上五类没有固定的顺序。
* 未经审视的初心很危险，包容的心态既安全舒服又有竞争力，自我实现在条件成熟时不可避免。